export const mockupForm = {
  status: true,
  data: {
    selectedIndex: 1,
    formItems: [
      {
        formKey: 'insurance',
        formTitleHTML:
          '<p style="line-height: 13pt; text-align: center; font-size: 10pt; color: rgba(36, 37, 61, 0.6); font-family: HelveticaNeue;">Nhận ít nhất <span style="font-weight: bold; color: rgb(214, 97, 0);">20%</span> tổng giá trị Hợp đồng Bảo hiểm bán được.</p>',
        footerTitleHTML: '<p>Các công ty <span>Bảo hiểm</span> hỗ trợ trên MFast</p>',
        secondButtonURL: '',
        mainButtonURL: '',
        listPartner: {
          items: [
            {
              label: 'Global Care',
              formTitleHTML:
                '<p style="line-height: 13pt; text-align: center; font-size: 10pt; color: rgba(36, 37, 61, 0.6); font-family: HelveticaNeue;">Nhận ít nhất <span style="font-weight: bold; color: rgb(214, 97, 0);">20%</span> tổng giá trị Hợp đồng Bảo hiểm bán được.</p>',
              imageUrl: 'https://appay-rc.cloudcms.vn/',
              documentUrl: '#',
            },
            {
              label: 'BHS Ticket',
              imageUrl: 'https://appay-rc.cloudcms.vn/',
              documentUrl: '#',
              listInsuranceType: [
                {
                  title: 'Mua lẻ',
                  formTitleHTML: '',
                  learnMoreURL: '',
                  mainButtonURL: '',
                  listFeatures: [
                    {
                      iconURL: '',
                      title: '',
                      featureURL: '',
                    },
                  ],
                },
              ],
            },
          ],
        },
      },
      {
        formKey: 'financial',
        formTitleHTML:
          '<p style="line-height: 13pt;text-align: center; font-size: 10pt; color: rgba(36, 37, 61, 0.6); font-family: HelveticaNeue;">Nhận ít nhất <span style="font-weight: bold; font-size: 10pt; color: #152872;">400,000đ</span> cho 1 khách hàng tham gia vay thành công.</p>',
        footerTitleHTML:
          '<p style="font-size: 10pt; color: rgba(36, 37, 61, 0.6);">Các công ty <span style="font-weight: 600; color: rgba(36, 37, 61, 0.8);">Tài chính</span> hỗ trợ trên MFast</p>',
        secondButtonURL: '',
        mainButtonURL: 'https://appay-rc.cloudcms.vn/mfast/application',
        listPartner: {
          items: [
            {
              label: 'FE Credit',
              imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/mfast/home_image/FE/Home@3x.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=1',
            },
            {
              label: 'VietCredit',
              imageUrl:
                'https://appay-rc.cloudcms.vn/https://www.vietcredit.vn//images/logo_v4.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=17',
            },
            {
              label: 'MCredit',
              imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/mfast/home_image/MB/Home@3x.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=2',
            },
            {
              label: 'FE TW',
              imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/mfast/home_image/TWL/Home@3x.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=5',
            },
            {
              label: 'SHB Finance',
              imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/mfast/home_image/SHB/Home@3x.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=6',
            },
            {
              label: 'Easy Credit',
              imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/mfast/home_image/Easy/Home@3x.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=7',
            },
            {
              label: 'FE - vay tự doanh',
              imageUrl:
                'https://appay-rc.cloudcms.vn/assets/img/mfast/home_image/KimAn/Home@3x.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=11',
            },
            {
              label: 'Snap',
              imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/mfast/home_image/Snap/Home@3x.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=14',
            },
            {
              label: 'TPBank',
              imageUrl:
                'https://appay-rc.cloudcms.vn/assets/img/mfast/home_image/TPBank/Home@3x.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=16',
            },
            {
              label: 'Atome',
              imageUrl: 'https://appay-rc.cloudcms.vn/https://m.atome.vn/_nuxt/img/f44d103.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=18',
            },
            {
              label: 'Cash24.vn',
              imageUrl:
                'https://appay-rc.cloudcms.vn/https://appay.cloudcms.vn/assets/img/project_logo/Cash24.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=19',
            },
            {
              label: 'F88',
              imageUrl:
                'https://appay-rc.cloudcms.vn/https://appay-rc.cloudcms.vn/assets/img/logo-F88-600x209.png',
              documentUrl: 'https://appay-rc.cloudcms.vn/Product_list?projectid=20',
            },
          ],
        },
        listRole: [
          {
            name: 'PreDSA',
            value: '282660',
          },
        ],
        policyDetailsUrl: '#',
      },
      {
        formKey: 'mobile_card',
        formTitleHTML:
          '<p style="line-height: 13pt;text-align: center; font-size: 10pt; color: rgba(36, 37, 61, 0.6); font-family: HelveticaNeue;">Nhận chiết khấu ít nhất <span style="font-weight: 600; color: rgb(0 ,130, 231);">3%</span> khi mua mã thẻ cào</p>',
        secondButtonURL: '',
        mainButtonURL: '',
        maxCanPurchase: 3,
        listPartner: {
          selectedIndex: 0,
          items: [
            {
              label: 'Viettel',
              description:
                '<p style="font-size: 10pt; color: rgba(36, 37, 61, 1); font-family: HelveticaNeue;">Chiết khấu <span style="font-weight: 600;">2.5%</span> khi mua </p>',
              imageUrl: 'https://appay-rc.cloudcms.vn//assets/img/card/vit.png',
              discount: '2.5',
              extraData: {
                telcoAlias: 'VTT',
              },
              listRouting: [
                {
                  price: '10000',
                  discount: '2.5',
                  provider_code: 'zota',
                },
                {
                  price: '20000',
                  discount: '2.5',
                  provider_code: 'zota',
                },
                {
                  price: '50000',
                  discount: '2.5',
                  provider_code: 'zota',
                },
                {
                  price: '100000',
                  discount: '2.5',
                  provider_code: 'zota',
                },
                {
                  price: '200000',
                  discount: '2.5',
                  provider_code: 'zota',
                },
                {
                  price: '500000',
                  discount: '2.5',
                  provider_code: 'zota',
                },
              ],
            },
            {
              label: 'Mobifone',
              description:
                '<p style="font-size: 10pt; color: rgba(36, 37, 61, 1); font-family: HelveticaNeue;">Chiết khấu <span style="font-weight: 600;">3.5%</span> khi mua </p>',
              imageUrl: 'https://appay-rc.cloudcms.vn//assets/img/card/mbf.png',
              discount: '3.5',
              extraData: {
                telcoAlias: 'VMS',
              },
              listRouting: [
                {
                  price: '10000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
                {
                  price: '20000',
                  discount: '2.5',
                  provider_code: 'zota',
                },
                {
                  price: '50000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
                {
                  price: '100000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
                {
                  price: '200000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
                {
                  price: '500000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
              ],
            },
            {
              label: 'Vinaphone',
              description:
                '<p style="font-size: 10pt; color: rgba(36, 37, 61, 1); font-family: HelveticaNeue;">Chiết khấu <span style="font-weight: 600;">3.5%</span> khi mua </p>',
              imageUrl: 'https://appay-rc.cloudcms.vn//assets/img/card/vnp.png',
              discount: '3.5',
              extraData: {
                telcoAlias: 'VNP',
              },
              listRouting: [
                {
                  price: '10000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
                {
                  price: '20000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
                {
                  price: '50000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
                {
                  price: '100000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
                {
                  price: '200000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
                {
                  price: '500000',
                  discount: '3.5',
                  provider_code: 'zota',
                },
              ],
            },
            {
              label: 'Vietnam Mobile',
              description:
                '<p style="font-size: 10pt; color: rgba(36, 37, 61, 1); font-family: HelveticaNeue;">Chiết khấu <span style="font-weight: 600;">4%</span> khi mua </p>',
              imageUrl: 'https://appay-rc.cloudcms.vn//assets/img/card/vnm.png',
              discount: '4',
              extraData: {
                telcoAlias: 'VNM',
              },
              listRouting: [
                {
                  price: '10000',
                  discount: '4',
                  provider_code: 'zota',
                },
                {
                  price: '20000',
                  discount: '4',
                  provider_code: 'zota',
                },
                {
                  price: '50000',
                  discount: '4',
                  provider_code: 'zota',
                },
                {
                  price: '100000',
                  discount: '4',
                  provider_code: 'zota',
                },
                {
                  price: '200000',
                  discount: '4',
                  provider_code: 'zota',
                },
                {
                  price: '500000',
                  discount: '4',
                  provider_code: 'zota',
                },
              ],
            },
            {
              label: 'GMobile',
              description:
                '<p style="font-size: 10pt; color: rgba(36, 37, 61, 1); font-family: HelveticaNeue;">Chiết khấu <span style="font-weight: 600;">4%</span> khi mua </p>',
              imageUrl: 'https://appay-rc.cloudcms.vn//assets/img/card/gte.png',
              discount: '4',
              extraData: {
                telcoAlias: 'GTE',
              },
              listRouting: [
                {
                  price: '10000',
                  discount: '4',
                  provider_code: 'zota',
                },
                {
                  price: '20000',
                  discount: '4',
                  provider_code: 'zota',
                },
                {
                  price: '50000',
                  discount: '4',
                  provider_code: 'zota',
                },
                {
                  price: '100000',
                  discount: '4',
                  provider_code: 'zota',
                },
                {
                  price: '200000',
                  discount: '4',
                  provider_code: 'zota',
                },
                {
                  price: '500000',
                  discount: '4',
                  provider_code: 'zota',
                },
              ],
            },
          ],
        },
      },
      {
        formKey: 'digital_wallet',
        formTitleHTML:
          '<p style="line-height: 13pt; text-align: center; font-size: 10pt; color: rgba(36, 37, 61, 0.6); font-family: HelveticaNeue;">Nhận ít nhất <span style="font-weight: bold; color: rgb(214, 97, 0);">20,000đ</span> cho 1 khách hàng mở ví thành công.</p>',
        footerTitleHTML:
          '<br>Các <span>Ví điện tử</span> hỗ trợ trên MFast</br> (Bấm vào logo để xem chi tiết sản phẩm và thu nhập)</p>',
        secondButtonURL: '',
        mainButtonURL: 'https://appay-rc.cloudcms.vn/smartpay/Smart_pay/home',
        listPartner: {
          items: [
            {
              label: 'Smartpay',
              imageUrl: 'https://appay-rc.cloudcms.vn/',
              documentUrl: 'https://appay-rc.cloudcms.vn/smartpay/Smart_pay/home',
            },
          ],
        },
      },
      {
        formKey: 'topup',
        formTitleHTML:
          '<p style="text-align: center; font-size: 12px; color: rgba(36, 37, 61, 0.6); font-family: HelveticaNeue">Chiếu khấu trực tiếp <span style="font-weight: bold; color: rgb(0, 134, 61)">10%</span> và nhận thêm <span style="font-weight: bold; color: rgb(0, 134, 61)">5%</span> thu nhập cho các nhà mạng hỗ trợ</p>',
        listPartner: {
          items: [
            {
              title: 'Trả trước',
              value: 'prepaid',
              telco: [
                {
                  name: 'Viettel',
                  value: 'vt',
                  imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/topup/viettel.png',
                },
                {
                  name: 'Mobifone',
                  value: 'mb',
                  imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/topup/mobifone.png',
                },
                {
                  name: 'Vinaphone',
                  value: 'vn',
                  imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/topup/vinaphone.png',
                },
              ],
              amount: [
                {
                  ori_price: 30000,
                  price: 27000,
                },
                {
                  ori_price: 40000,
                  price: 36000,
                },
                {
                  ori_price: 50000,
                  price: 45000,
                },
                {
                  ori_price: 100000,
                  price: 90000,
                },
                {
                  ori_price: 200000,
                  price: 180000,
                },
                {
                  ori_price: 250000,
                  price: 225000,
                },
              ],
            },
            {
              title: 'Trả sau',
              value: 'postpaid',
              telco: [
                {
                  name: 'Viettel',
                  value: 'viettel',
                  imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/topup/viettel.png',
                },
                {
                  name: 'Vinaphone',
                  value: 'vinaphone',
                  imageUrl: 'https://appay-rc.cloudcms.vn/assets/img/topup/vinaphone.png',
                },
              ],
              amount: [
                {
                  ori_price: 50000,
                  price: 45000,
                },
                {
                  ori_price: 100000,
                  price: 90000,
                },
                {
                  ori_price: 150000,
                  price: 135000,
                },
                {
                  ori_price: 200000,
                  price: 180000,
                },
                {
                  ori_price: 250000,
                  price: 225000,
                },
              ],
            },
          ],
        },
      },
    ],
    policyDefaultHtml:
      '\n            <p style="margin-bottom: 10px; text-align: center; font-size: 10pt; color: rgba(36, 37, 61, 1); font-family: HelveticaNeue;">MFast sử dụng thông tin trên với mục đích:</p>\n            <ul>\n            \n                <li>- Để thực hiện các nghĩa vụ của APPAY theo bất kỳ thỏa thuận nào được ký kết với khách hàng;</li>\n    \n                <li>- Để cung cấp cho khách hàng bất kỳ dịch vụ hợp pháp nào mà khách hàng yêu cầu;</li>\n                \n                <li>- Để xử lý các đăng ký của khách hàng và để cung cấp các dịch vụ cho khách hàng;</li>\n                \n                <li>- Khi khách hàng yêu cầu tải xuống và sử dụng ứng dụng APPAY, hoặc để xử lý yêu cầu của khách hàng, để cung cấp ứng dụng cho khách hàng và để cung cấp cho khách hàng giấy phép sử dụng ứng dụng;</li>\n                \n                <li>- Để xử lý việc tham gia của khách hàng vào bất kỳ sự kiện, hoạt động, nhóm trọng điểm, nghiên cứu, cuộc thi, chương trình khuyến mại, cuộc bình chọn, khảo sát hoặc sản phẩm nào;</li>\n                \n                <li>- Để xử lý, quản lý hoặc xác minh việc đăng ký theo dõi của khách hàng đối với APPAY và để cung cấp cho khách hàng các lợi ích dành cho người theo dõi;</li>\n                \n                <li>- Để xác nhận, và xử lý các thanh toán liên quan đến bất kỳ dịch vụ nào mà khách hàng đã yêu cầu;</li>\n                \n            </ul>\n        ',
  },
};

export const mockupListDistrict = {
  1: 'Q. Ba Đình - Hà Nội',
  2: 'Q. Tây Hồ - Hà Nội',
  3: 'Q. Hoàn Kiếm - Hà Nội',
  4: 'Q. Hai Bà Trưng - Hà Nội',
  5: 'Q. Đống Đa - Hà Nội',
  6: 'Q. Thanh Xuân - Hà Nội',
  7: 'Q. Cầu Giấy - Hà Nội',
  8: 'H. Sóc Sơn - Hà Nội',
  9: 'H. Đông Anh - Hà Nội',
  10: 'H. Gia Lâm - Hà Nội',
  11: 'Q.Bắc Từ Liêm - Hà Nội',
  12: 'H. Thanh Trì - Hà Nội',
  13: 'Q. Hoàng Mai - Hà Nội',
  14: 'Q. Long Biên - Hà Nội',
  15: 'Q. Hà Đông - Hà Nội',
  16: 'TX. Sơn Tây - Hà Nội',
  17: 'H. Ba Vì - Hà Nội',
  18: 'H. Phúc Thọ - Hà Nội',
  19: 'H. Đan Phượng - Hà Nội',
  20: 'H. Thạch Thất - Hà Nội',
  21: 'H. Hoài Đức - Hà Nội',
  22: 'H. Quốc Oai - Hà Nội',
  23: 'H. Chương Mỹ - Hà Nội',
  24: 'H. Thanh Oai - Hà Nội',
  25: 'H. Thường Tín - Hà Nội',
  26: 'H. Mỹ Đức - Hà Nội',
  27: 'H. Ứng Hòa - Hà Nội',
  28: 'H. Phú Xuyên - Hà Nội',
  29: 'H. Mê Linh - Hà Nội',
  690: 'Q. Nam Từ Liêm - Hà Nội',
  30: 'TP. Tuyên Quang - Tuyên Quang',
  31: 'H. Na Hang - Tuyên Quang',
  32: 'H. Chiêm Hóa - Tuyên Quang',
  33: 'H. Hàm Yên - Tuyên Quang',
  34: 'H. Yên Sơn - Tuyên Quang',
  35: 'H. Sơn Dương - Tuyên Quang',
  691: 'H. Lâm Bình - Tuyên Quang',
  36: 'TP Hà Giang - Hà Giang',
  37: 'H. Đồng Văn - Hà Giang',
  38: 'H. Mèo Vạc - Hà Giang',
  39: 'H. Yên Minh - Hà Giang',
  40: 'H. Quản Bạ - Hà Giang',
  41: 'H. Bắc Mê - Hà Giang',
  42: 'H. Hoàng Su Phì - Hà Giang',
  43: 'H. Vị Xuyên - Hà Giang',
  44: 'H. Xín Mần - Hà Giang',
  45: 'H.Bắc Quang - Hà Giang',
  46: 'H.Quang Bình - Hà Giang',
  47: 'TP Cao Bằng - Cao Bằng',
  48: 'H. Bảo Lạc - Cao Bằng',
  49: 'H. Hà Quảng - Cao Bằng',
  50: 'H. Thông Nông - Cao Bằng',
  51: 'H. Trà Lĩnh - Cao Bằng',
  52: 'H. Trùng Khánh - Cao Bằng',
  53: 'H. Nguyên Bình - Cao Bằng',
  54: 'H. Hòa An - Cao Bằng',
  55: 'H. Quảng Uyên - Cao Bằng',
  56: 'H. Hạ Lang - Cao Bằng',
  57: 'H. Thạch An - Cao Bằng',
  58: 'H. Bảo Lâm - Cao Bằng',
  59: 'H. Phục Hòa - Cao Bằng',
  60: 'TP Lạng Sơn - Lạng Sơn',
  61: 'H. Tràng Định - Lạng Sơn',
  62: 'H. Văn Lãng - Lạng Sơn',
  63: 'H. Bình Gia - Lạng Sơn',
  64: 'H. Bắc Sơn - Lạng Sơn',
  65: 'H. Văn Quan - Lạng Sơn',
  66: 'H. Cao Lộc - Lạng Sơn',
  67: 'H. Lộc Bình - Lạng Sơn',
  68: 'H. Chi Lăng - Lạng Sơn',
  69: 'H. Đình Lập - Lạng Sơn',
  70: 'H. Hữu Lũng - Lạng Sơn',
  71: 'TP Bắc Cạn - Bắc Cạn',
  72: 'H. Ba Bể - Bắc Cạn',
  73: 'H. Ngân Sơn - Bắc Cạn',
  74: 'H. Chợ Đồn - Bắc Cạn',
  75: 'H. Na Rì - Bắc Cạn',
  76: 'H. Bạch Thông - Bắc Cạn',
  77: 'H. Chợ Mới - Bắc Cạn',
  78: 'H. Pác Nặm - Bắc Cạn',
  79: 'TP Thái Nguyên - Thái Nguyên',
  80: 'TP Sông Công - Thái Nguyên',
  81: 'H. Định Hóa - Thái Nguyên',
  82: 'H. Võ Nhai - Thái Nguyên',
  83: 'H. Phú Lương - Thái Nguyên',
  84: 'H. Đồng Hỷ - Thái Nguyên',
  85: 'H. Đại Từ - Thái Nguyên',
  86: 'H. Phú Bình - Thái Nguyên',
  87: 'TX. Phổ Yên - Thái Nguyên',
  88: 'TP Yên Bái - Yên Bái',
  89: 'TX Nghĩa Lộ - Yên Bái',
  90: 'H. Lục Yên - Yên Bái',
  91: 'H. Văn Yên - Yên Bái',
  92: 'H. Mù Cang Chải - Yên Bái',
  93: 'H. Trấn Yên - Yên Bái',
  94: 'H. Yên Bình - Yên Bái',
  95: 'H. Văn Chấn - Yên Bái',
  96: 'H. Trạm Tấu - Yên Bái',
  97: 'TP Lào Cai - Lào Cai',
  98: 'H. Si Ma Cai - Lào Cai',
  99: 'H. Mường Khương - Lào Cai',
  100: 'H. Bát Xát - Lào Cai',
  101: 'H. Bắc Hà - Lào Cai',
  102: 'H. Bảo Thắng - Lào Cai',
  103: 'H. Sa Pa - Lào Cai',
  104: 'H. Bảo Yên - Lào Cai',
  105: 'H. Văn Bàn - Lào Cai',
  106: 'TP Điện Biên Phủ - Điện Biên',
  107: 'TX Mường Lay - Điện Biên',
  108: 'H. Tủa Chùa - Điện Biên',
  109: 'H. Tuần Giáo - Điện Biên',
  110: 'H. Điện Biên - Điện Biên',
  111: 'H. Điện Biên Đông - Điện Biên',
  112: 'H. Mường Chà - Điện Biên',
  113: 'H. Mường Nhé - Điện Biên',
  114: 'H. Mường Ảng - Điện Biên',
  692: 'H. Nậm Pồ - Điện Biên',
  115: 'TP Sơn La - Sơn La',
  116: 'H. Quỳnh Nhai - Sơn La',
  117: 'H. Mường La - Sơn La',
  118: 'H. Thuận Châu - Sơn La',
  119: 'H. Bắc Yên - Sơn La',
  120: 'H. Phù Yến - Sơn La',
  121: 'H. Mai Sơn - Sơn La',
  122: 'H. Sông Mã - Sơn La',
  123: 'H. Yên Châu - Sơn La',
  124: 'H. Mộc Châu - Sơn La',
  125: 'H. Sốp Cộp - Sơn La',
  693: 'H. Vân Hồ - Sơn La',
  126: 'TP Lai Châu - Lai Châu',
  127: 'H. Mường Tè - Lai Châu',
  128: 'H. Sìn Hồ - Lai Châu',
  129: 'H. Tam Đường - Lai Châu',
  130: 'H. Than Uyên - Lai Châu',
  131: 'H. Phong Thổ - Lai Châu',
  694: 'H. Tân Uyên - Lai Châu',
  695: 'H. Nậm Nhùn - Lai Châu',
  132: 'TP Hạ Long - Quảng Ninh',
  133: 'TP Cẩm Phả - Quảng Ninh',
  134: 'TP Uông Bí - Quảng Ninh',
  135: 'TP Móng Cái - Quảng Ninh',
  136: 'H. Bình Liêu - Quảng Ninh',
  137: 'H. Đầm Hà - Quảng Ninh',
  138: 'H. Tiên Yên - Quảng Ninh',
  139: 'H. Ba Chẽ - Quảng Ninh',
  140: 'H. Vân Đồn - Quảng Ninh',
  141: 'H. Hoàng Bồ - Quảng Ninh',
  142: 'TX Đông Triều - Quảng Ninh',
  143: 'H. Cô Tô - Quảng Ninh',
  144: 'TX Quảng Yên - Quảng Ninh',
  145: 'H. Hải Hà - Quảng Ninh',
  146: 'Q. Hồng Bàng - Hải Phòng',
  147: 'Q. Ngô Quyền - Hải Phòng',
  148: 'Q, Lê Chân - Hải Phòng',
  149: 'Q. Kiến An - Hải Phòng',
  150: 'Q. Đồ Sơn - Hải Phòng',
  151: 'H. Thủy Nguyên - Hải Phòng',
  152: 'Q. Hải An - Hải Phòng',
  153: 'H. An Lão - Hải Phòng',
  154: 'H. Kiến Thụy - Hải Phòng',
  155: 'H. Tiên Lãng - Hải Phòng',
  156: 'H. Vĩnh Bảo - Hải Phòng',
  157: 'H. Cát Hải - Hải Phòng',
  158: 'H. An Dương - Hải Phòng',
  688: 'H Bạch Long Vĩ - Hải Phòng',
  689: 'Q. Dương Kinh - Hải Phòng',
  159: 'TP Hải Dương - Hải Dương',
  160: 'TX Chí Linh - Hải Dương',
  161: 'H. Nam Sách - Hải Dương',
  162: 'H. Thanh Hà - Hải Dương',
  163: 'H. Kinh Môn - Hải Dương',
  164: 'H. Kim Thành - Hải Dương',
  165: 'H. Gia Lộc - Hải Dương',
  166: 'H. Tứ Kỳ - Hải Dương',
  167: 'H. Cẩm Giàng - Hải Dương',
  168: 'H. Bình Giang - Hải Dương',
  169: 'H. Thanh Miện - Hải Dương',
  170: 'H. Ninh Giang - Hải Dương',
  171: 'TP Hưng Yên - Hưng Yên',
  172: 'H. Mỹ Hào - Hưng Yên',
  173: 'H. Văn Giang - Hưng Yên',
  174: 'H. Ân Thi - Hưng Yên',
  175: 'H. Kim Động - Hưng Yên',
  176: 'H. Phù Cừ - Hưng Yên',
  177: 'H. Tiên Lữ - Hưng Yên',
  178: 'H. Khoái Châu - Hưng Yên',
  179: 'H. Văn Lâm - Hưng Yên',
  180: 'H. Yên Mỹ - Hưng Yên',
  181: 'TP Bắc Giang - Bắc Giang',
  182: 'H. Yên Thế - Bắc Giang',
  183: 'H. Tân Yên - Bắc Giang',
  184: 'H. Lục Ngạn - Bắc Giang',
  185: 'H. Hiệp Hòa - Bắc Giang',
  186: 'H. Lạng Giang - Bắc Giang',
  187: 'H. Sơn Động - Bắc Giang',
  188: 'H. Lục Nam - Bắc Giang',
  189: 'H. Việt Yên - Bắc Giang',
  190: 'H. Yên Dũng - Bắc Giang',
  191: 'TP Bắc Ninh - Bắc Ninh',
  192: 'TX Từ Sơn - Bắc Ninh',
  193: 'H. Yên Phong - Bắc Ninh',
  194: 'H. Quế Võ - Bắc Ninh',
  195: 'H. Tiên Du - Bắc Ninh',
  196: 'H. Thuận Thành - Bắc Ninh',
  197: 'H. Gia Bình - Bắc Ninh',
  198: 'H. Lương Tài - Bắc Ninh',
  199: 'TP Việt Trì - Phú Thọ',
  200: 'TX Phú Thọ - Phú Thọ',
  201: 'H. Đoan Hùng - Phú Thọ',
  202: 'H. Hạ Hòa - Phú Thọ',
  203: 'H. Thanh Ba - Phú Thọ',
  204: 'H. Thanh Thủy - Phú Thọ',
  205: 'H. Lâm Thao - Phú Thọ',
  206: 'H. Yên Lập - Phú Thọ',
  207: 'H. Tam Nông - Phú Thọ',
  208: 'H. Thanh Sơn - Phú Thọ',
  209: 'H. Cẩm Khê - Phú Thọ',
  210: 'H. Phù Ninh - Phú Thọ',
  211: 'H. Tân Sơn - Phú Thọ',
  212: 'TP Vĩnh Yên - Vĩnh Phúc',
  213: 'H. Lập Thạch - Vĩnh Phúc',
  214: 'H. Tam Dương - Vĩnh Phúc',
  215: 'H. Vĩnh Tường - Vĩnh Phúc',
  216: 'H. Yên Lạc - Vĩnh Phúc',
  217: 'H. Tam Đảo - Vĩnh Phúc',
  218: 'H. Bình Xuyên - Vĩnh Phúc',
  219: 'TX Phúc Yên - Vĩnh Phúc',
  696: 'H. Sông Lô - Vĩnh Phúc',
  220: 'TP Hòa Bình - Hòa Bình',
  221: 'H. Đà Bắc - Hòa Bình',
  222: 'H. Mai Châu - Hòa Bình',
  223: 'H. Kỳ Sơn - Hòa Bình',
  224: 'H. Lương Sơn - Hòa Bình',
  225: 'H. Kim Bôi - Hòa Bình',
  226: 'H. Tân Lạc - Hòa Bình',
  227: 'H. Lạc Sơn - Hòa Bình',
  228: 'H. Lạc Thủy - Hòa Bình',
  229: 'H. Yên Thủy - Hòa Bình',
  697: 'H. Cao Phong - Hòa Bình',
  240: 'TP Phủ Lý - Hà Nam',
  241: 'H. Duy Tiên - Hà Nam',
  242: 'H. Kim Bảng - Hà Nam',
  243: 'H.Lý Nhân       - Hà Nam',
  244: 'H. Thanh Liêm - Hà Nam',
  245: 'H. Bình Lục - Hà Nam',
  230: 'TP Nam Định - Nam Định',
  231: 'H. Vụ Bản - Nam Định',
  232: 'H. Mỹ Lộc - Nam Định',
  233: 'H. Ý Yên - Nam Định',
  234: 'H. Nam Trực - Nam Định',
  235: 'H. Trực Ninh - Nam Định',
  236: 'H. Xuân Trường - Nam Định',
  237: 'H. Giao Thủy - Nam Định',
  238: 'H. Nghĩa Hưng - Nam Định',
  239: 'H. Hải Hậu - Nam Định',
  246: 'TP Ninh Bình - Ninh Bình',
  247: 'TP Tam Điệp - Ninh Bình',
  248: 'H. Nho Quan - Ninh Bình',
  249: 'H. Gia Viễn - Ninh Bình',
  250: 'H. Hoa Lư - Ninh Bình',
  251: 'H. Yên Mô - Ninh Bình',
  252: 'H. Yên Khánh - Ninh Bình',
  253: 'H. Kim Sơn - Ninh Bình',
  254: 'TP Thái Bình - Thái Bình',
  255: 'H. Quỳnh Phụ - Thái Bình',
  256: 'H. Hưng Hà - Thái Bình',
  257: 'H. Thái Thụy - Thái Bình',
  258: 'H. Đông Hưng - Thái Bình',
  259: 'H. Vũ Thư - Thái Bình',
  260: 'H. Kiến Xương - Thái Bình',
  261: 'H. Tiền Hải - Thái Bình',
  262: 'TP Thanh Hóa - Thanh Hóa',
  263: 'TX Bỉm Sơn - Thanh Hóa',
  264: 'TX Sầm Sơn - Thanh Hóa',
  265: 'H. Mường Lát - Thanh Hóa',
  266: 'H. Quan Hóa - Thanh Hóa',
  267: 'H. Quan Sơn - Thanh Hóa',
  268: 'H. Bá Thước - Thanh Hóa',
  269: 'H. Cẩm Thủy - Thanh Hóa',
  270: 'H. Lang Chánh - Thanh Hóa',
  271: 'H. Thạch Thành - Thanh Hóa',
  272: 'H. Ngọc Lặc - Thanh Hóa',
  273: 'H. Thường Xuân - Thanh Hóa',
  274: 'H. Như Xuân - Thanh Hóa',
  275: 'H. Như Thanh - Thanh Hóa',
  276: 'H. Vĩnh Lộc - Thanh Hóa',
  277: 'H. Hà Trung - Thanh Hóa',
  278: 'H. Nga Sơn - Thanh Hóa',
  279: 'H. Yên Định - Thanh Hóa',
  280: 'H. Thọ Xuân - Thanh Hóa',
  281: 'H. Hậu Lộc - Thanh Hóa',
  282: 'H. Thiệu Hóa - Thanh Hóa',
  283: 'H. Hoằng Hóa - Thanh Hóa',
  284: 'H. Đông Sơn - Thanh Hóa',
  285: 'H. Triệu Sơn - Thanh Hóa',
  286: 'H. Quảng Xương - Thanh Hóa',
  287: 'H. Nông Cống - Thanh Hóa',
  288: 'H. Tĩnh Gia - Thanh Hóa',
  289: 'TP Vinh - Nghệ An',
  290: 'TX Cửa Lò - Nghệ An',
  291: 'H. Quế Phong - Nghệ An',
  292: 'H. Quỳ Châu - Nghệ An',
  293: 'H. Kỳ Sơn - Nghệ An',
  294: 'H. Quỳ Hợp - Nghệ An',
  295: 'H. Nghĩa Đàn - Nghệ An',
  296: 'H. Tương Dương - Nghệ An',
  297: 'H. Quỳnh Lưu - Nghệ An',
  298: 'H. Tân Kỳ - Nghệ An',
  299: 'H. Con Cuông - Nghệ An',
  300: 'H. Yên Thành - Nghệ An',
  301: 'H. Diễn Châu - Nghệ An',
  302: 'H. Anh Sơn - Nghệ An',
  303: 'H. Đô Lương - Nghệ An',
  304: 'H. Thanh Chương - Nghệ An',
  305: 'H. Nghi Lộc - Nghệ An',
  306: 'H. Nam Đàn - Nghệ An',
  307: 'H. Hưng Nguyên - Nghệ An',
  308: 'TX Thái Hòa - Nghệ An',
  698: 'TX Hoàng Mai - Nghệ An',
  309: 'TP Hà Tĩnh - Hà Tĩnh',
  310: 'TX Hồng Lĩnh - Hà Tĩnh',
  311: 'H. Nghi Xuân - Hà Tĩnh',
  312: 'H. Đức Thọ - Hà Tĩnh',
  313: 'H. Hương Sơn - Hà Tĩnh',
  314: 'H. Can Lộc - Hà Tĩnh',
  315: 'H. Thạch Hà - Hà Tĩnh',
  316: 'H. Cẩm Xuyên - Hà Tĩnh',
  317: 'H. Hương Khê - Hà Tĩnh',
  318: 'TX Kỳ Anh - Hà Tĩnh',
  319: 'H. Vũ Quang - Hà Tĩnh',
  320: 'H. Lộc Hà - Hà Tĩnh',
  699: 'H. Kỳ Anh - Hà Tĩnh',
  321: 'TP Đồng Hới - Quảng Bình',
  322: 'H. Tuyên Hóa - Quảng Bình',
  323: 'H. Minh Hóa - Quảng Bình',
  324: 'H. Quảng Trạch - Quảng Bình',
  325: 'H. Bố Trạch - Quảng Bình',
  326: 'H. Quảng Ninh - Quảng Bình',
  327: 'H. Lệ Thủy - Quảng Bình',
  700: 'TX Ba Đồn - Quảng Bình',
  328: 'TP Đông Hà - Quảng Trị',
  329: 'TX Quảng Trị - Quảng Trị',
  330: 'H. Vĩnh Linh - Quảng Trị',
  331: 'H. Gio Linh - Quảng Trị',
  332: 'H. Cam Lộ - Quảng Trị',
  333: 'H. Triệu Phong - Quảng Trị',
  334: 'H. Hải Lăng - Quảng Trị',
  335: 'H. Hướng Hóa - Quảng Trị',
  336: 'H. Đa Krông - Quảng Trị',
  701: 'H. Cồn Cỏ - Quảng Trị',
  337: 'TP Huế - Thừa Thiên- Huế',
  338: 'H. Quảng Điền - Thừa Thiên- Huế',
  339: 'H. Phong Điền - Thừa Thiên- Huế',
  340: 'TX Hương Trà - Thừa Thiên- Huế',
  341: 'H. Phú Vang - Thừa Thiên- Huế',
  342: 'TX Hương Thủy - Thừa Thiên- Huế',
  343: 'H. Phú Lộc - Thừa Thiên- Huế',
  344: 'H. A Lưới - Thừa Thiên- Huế',
  345: 'H. Nam Đông - Thừa Thiên- Huế',
  346: 'Q. Hải Châu - Đà Nẵng',
  347: 'Q. Thanh Khê - Đà Nẵng',
  348: 'Q. Sơn Trà - Đà Nẵng',
  349: 'Q. Ngũ Hành Sơn - Đà Nẵng',
  350: 'Q. Liên Chiểu - Đà Nẵng',
  351: 'H. Hòa Vang - Đà Nẵng',
  702: 'Q. Cẩm Lệ - Đà Nẵng',
  703: 'H. Hoàng Sa - Đà Nẵng',
  352: 'TP Tam Kỳ - Quảng Nam',
  353: 'TP Hội An - Quảng Nam',
  354: 'H. Đông Giang - Quảng Nam',
  355: 'H. Đại Lộc - Quảng Nam',
  356: 'TX Điện Bàn - Quảng Nam',
  357: 'H. Duy Xuyên - Quảng Nam',
  358: 'H. Nam Giang - Quảng Nam',
  359: 'H. Thăng Bình - Quảng Nam',
  360: 'H. Quế Sơn - Quảng Nam',
  361: 'H. Hiệp Đức - Quảng Nam',
  362: 'H. Tiên Phước - Quảng Nam',
  363: 'H. Phước Sơn - Quảng Nam',
  364: 'H. Núi Thành - Quảng Nam',
  365: 'H. Bắc Trà My - Quảng Nam',
  366: 'H. Nam Trà My - Quảng Nam',
  367: 'H. Tây Giang - Quảng Nam',
  368: 'H. Nông Sơn - Quảng Nam',
  369: 'H. Phú Ninh - Quảng Nam',
  370: 'TP Quảng Ngãi - Quảng Ngãi',
  371: 'H. Lý Sơn - Quảng Ngãi',
  372: 'H. Bình Sơn - Quảng Ngãi',
  373: 'H. Trà Bồng - Quảng Ngãi',
  374: 'H. Sơn Tinh - Quảng Ngãi',
  375: 'H. Sơn Tây - Quảng Ngãi',
  376: 'H. Sơn Hà - Quảng Ngãi',
  377: 'H. Tư Nghĩa - Quảng Ngãi',
  378: 'H. Nghĩa Hành - Quảng Ngãi',
  379: 'H. Minh Long - Quảng Ngãi',
  380: 'H. Mộ Đức - Quảng Ngãi',
  381: 'H. Đức Phổ - Quảng Ngãi',
  382: 'H. Ba Tơ - Quảng Ngãi',
  383: 'H. Tây Trà - Quảng Ngãi',
  384: 'TP Quy Nhơn - Bình Định',
  385: 'H. An Lão - Bình Định',
  386: 'H. Hoài Nhơn - Bình Định',
  387: 'H. Hoài Ân - Bình Định',
  388: 'H. Phù Mỹ - Bình Định',
  389: 'H. Vĩnh Thạnh - Bình Định',
  390: 'H. Phù Cát - Bình Định',
  391: 'H. Tây Sơn - Bình Định',
  392: 'H. An Nhơn - Bình Định',
  393: 'H. Tuy Phước - Bình Định',
  394: 'H. Vân Canh - Bình Định',
  395: 'TP Tuy Hòa - Phú Yên',
  396: 'H. Đồng Xuân - Phú Yên',
  397: 'TX Sông Cầu - Phú Yên',
  398: 'H. Tuy An - Phú Yên',
  399: 'H. Sơn Hòa - Phú Yên',
  400: 'H.Tay Hoa                    - Phú Yên',
  401: 'H. Sông Hinh - Phú Yên',
  402: 'H. Phú Hòa - Phú Yên',
  403: 'H. Đông Hòa - Phú Yên',
  404: 'TP Nha Trang - Khánh Hòa',
  405: 'H. Vạn Ninh - Khánh Hòa',
  406: 'TX Ninh Hòa - Khánh Hòa',
  407: 'H. Diên Khánh - Khánh Hòa',
  408: 'TP Cam Ranh - Khánh Hòa',
  409: 'H. Khánh Vĩnh - Khánh Hòa',
  410: 'H. Khánh Sơn - Khánh Hòa',
  411: 'H. Trường Sa - Khánh Hòa',
  412: 'H. Cam Lâm - Khánh Hòa',
  413: 'TP Phan Thiết - Bình Thuận',
  414: 'TX La Gi - Bình Thuận',
  415: 'H. Tuy Phong - Bình Thuận',
  416: 'H. Bắc Bình - Bình Thuận',
  417: 'H. Hàm Thuận Bắc - Bình Thuận',
  418: 'H. Hàm Thuận Nam - Bình Thuận',
  419: 'H. Tánh Linh - Bình Thuận',
  420: 'H. Hàm Tân - Bình Thuận',
  421: 'H. Đức Linh - Bình Thuận',
  422: 'H. Phú Quý - Bình Thuận',
  423: 'TP Phan Rang - Tháp Chàm - Ninh Thuận',
  424: 'H. Ninh Sơn - Ninh Thuận',
  425: 'H. Ninh Hải - Ninh Thuận',
  426: 'H. Ninh Phước - Ninh Thuận',
  427: 'H. Thuận Bắc - Ninh Thuận',
  428: 'H. Bắc Ái - Ninh Thuận',
  704: 'H. Thuận Nam - Ninh Thuận',
  429: 'TP Pleiku - Gia Lai ',
  430: "H. K'Bang - Gia Lai ",
  431: 'H. Đắk Đoa - Gia Lai ',
  432: 'H. Chư Păh - Gia Lai ',
  433: 'H. Ia Grai - Gia Lai ',
  434: 'TX An Khê - Gia Lai ',
  435: 'H. Kông Chro - Gia Lai ',
  436: 'H. Đức Cơ - Gia Lai ',
  437: 'H. Chư Prông - Gia Lai ',
  438: 'H. Chư Sê - Gia Lai ',
  439: 'TX Ayun Pa - Gia Lai ',
  440: 'H. Krông Pa - Gia Lai ',
  441: 'H. Phú Thiện - Gia Lai ',
  442: 'H. Mang Yang - Gia Lai ',
  443: 'H. Đak Pơ - Gia Lai ',
  444: 'H. Ia Pa - Gia Lai ',
  705: 'H. Chư Pưh - Gia Lai ',
  445: 'Q. 1 - Hồ Chí Minh',
  446: 'Q. 2 - Hồ Chí Minh',
  447: 'Q. 3 - Hồ Chí Minh',
  448: 'Q. 4 - Hồ Chí Minh',
  449: 'Q. 5 - Hồ Chí Minh',
  450: 'Q. 6 - Hồ Chí Minh',
  451: 'Q. 7 - Hồ Chí Minh',
  452: 'Q. 8 - Hồ Chí Minh',
  453: 'Q. 9 - Hồ Chí Minh',
  454: 'Q. 10 - Hồ Chí Minh',
  455: 'Q. 11 - Hồ Chí Minh',
  456: 'Q. 12 - Hồ Chí Minh',
  457: 'Q. Gò Vấp - Hồ Chí Minh',
  458: 'Q. Tân Bình - Hồ Chí Minh',
  459: 'Q. Bình Thạnh - Hồ Chí Minh',
  460: 'Q. Phú Nhuận - Hồ Chí Minh',
  461: 'Q. Thủ Đức - Hồ Chí Minh',
  462: 'Q. Tân Phú - Hồ Chí Minh',
  463: 'Q. Bình Tân - Hồ Chí Minh',
  464: 'H. Củ Chi - Hồ Chí Minh',
  465: 'H. Nhà Bè - Hồ Chí Minh',
  466: 'H. Bình Chánh - Hồ Chí Minh',
  467: 'H. Hóc Môn - Hồ Chí Minh',
  468: 'H. Cần Giờ - Hồ Chí Minh',
  469: 'TP Kon Tum - Kontum',
  470: 'H Đắk Glei - Kontum',
  471: 'H. Ngọc Hồi - Kontum',
  472: 'H. Đắk Tô - Kontum',
  473: 'H. Kon Plông - Kontum',
  474: 'H. Đắk Hà - Kontum',
  475: 'H. Sa Thầy - Kontum',
  476: 'H. Tu Mơ Rông - Kontum',
  706: "H. Ia H'Drai - Kontum",
  707: 'H. Kon Rẫy - Kontum',
  477: 'TP Buôn Ma Thuột - Đắk Lắk',
  478: "H. Ea H'leo - Đắk Lắk",
  479: 'H. Ea Súp - Đắk Lắk',
  480: 'H. Krông Năng - Đắk Lắk',
  481: 'H. Krông Buk - Đắk Lắk',
  482: 'H. Buôn Đôn - Đắk Lắk',
  483: "H. Cư M'gar                   - Đắk Lắk",
  484: 'H. Ea Kar  - Đắk Lắk',
  485: "H. M'Drak  - Đắk Lắk",
  486: 'H. Krông Pak - Đắk Lắk',
  487: 'H. Cư Kuin  - Đắk Lắk',
  488: 'H. Krông Ana  - Đắk Lắk',
  489: 'H. Krông Bông - Đắk Lắk',
  490: 'H. Lắk - Đắk Lắk',
  491: 'TX  Buôn Hồ - Đắk Lắk',
  492: 'TX Gia Nghĩa - Đắk Nông',
  493: 'H. Đắk Mil - Đắk Nông',
  494: 'H. Krông Nô - Đắk Nông',
  495: 'H. Đắk Song - Đắk Nông',
  496: "H. Đắk R'Lấp - Đắk Nông",
  497: 'H. Đắk Glong - Đắk Nông',
  498: 'H. Cư Jút - Đắk Nông',
  499: 'H. Tuy Đức - Đắk Nông',
  500: 'TP Đà Lạt - Lâm Đồng',
  501: 'TP Bảo Lộc - Lâm Đồng',
  502: 'H. Lạc Dương - Lâm Đồng',
  503: 'H. Đơn Dương - Lâm Đồng',
  504: 'H. Đức Trọng - Lâm Đồng',
  505: 'H. Lâm Hà - Lâm Đồng',
  506: 'H. Bảo Lâm - Lâm Đồng',
  507: 'H. Di Linh - Lâm Đồng',
  508: 'H. Đà Huoai - Lâm Đồng',
  509: 'H. Đà Tẻh - Lâm Đồng',
  510: 'H. Cát Tiên - Lâm Đồng',
  511: 'H. Đam Rông - Lâm Đồng',
  512: 'TP Thủ Dầu Một - Bình Dương',
  513: 'TX Bến Cát - Bình Dương',
  514: 'TX Tân Uyên - Bình Dương',
  515: 'TX Thuận An - Bình Dương',
  516: 'H. Dầu Tiếng - Bình Dương',
  517: 'H. Phú Giao - Bình Dương',
  518: 'TX Dĩ An - Bình Dương',
  708: 'H. Bắc Tân Uyên - Bình Dương',
  709: 'H. Bàu Bàng - Bình Dương',
  519: 'TX Đồng Xoài - Bình Phước',
  520: 'H. Đồng Phú - Bình Phước',
  521: 'H. Hớn Quản - Bình Phước',
  522: 'H. Lộc Ninh - Bình Phước',
  523: 'H. Phú Riềng - Bình Phước',
  524: 'TX Phước Long - Bình Phước',
  525: 'TX Bình Long - Bình Phước',
  526: 'H. Chơn Thành - Bình Phước',
  681: 'H. Bù Đăng - Bình Phước',
  682: 'H. Bù Đốp - Bình Phước',
  683: 'H. Bù Gia Mập - Bình Phước',
  527: 'TP Tây Ninh - Tây Ninh',
  528: 'H. Tân Biên - Tây Ninh',
  529: 'H. Tân Châu - Tây Ninh',
  530: 'H. Dương Minh Châu - Tây Ninh',
  531: 'H. Châu Thành - Tây Ninh',
  532: 'H. Hòa Thành - Tây Ninh',
  533: 'H. Bến Cầu - Tây Ninh',
  534: 'H. Gò Dầu - Tây Ninh',
  535: 'H. Trảng Bàng - Tây Ninh',
  536: 'TP Biên Hòa - Đồng Nai',
  537: 'TX Long Khánh - Đồng Nai',
  538: 'H. Định Quán - Đồng Nai',
  539: 'H. Vĩnh Cửu - Đồng Nai',
  540: 'H. Thống Nhất - Đồng Nai',
  541: 'H. Tân Phú - Đồng Nai',
  542: 'H. Xuân Lộc - Đồng Nai',
  543: 'H. Long Thành - Đồng Nai',
  544: 'H. Nhơn Trạch - Đồng Nai',
  545: 'H. Trảng Bom - Đồng Nai',
  546: 'H. Cẩm Mỹ - Đồng Nai',
  547: 'TP Vũng Tàu - Bà Rịa- Vũng Tàu',
  548: 'TP Bà Rịa - Bà Rịa- Vũng Tàu',
  549: 'H. Châu Đức - Bà Rịa- Vũng Tàu',
  550: 'H. Xuyên Mộc - Bà Rịa- Vũng Tàu',
  551: 'H. Tân Thành - Bà Rịa- Vũng Tàu',
  552: 'H. Long Điền - Bà Rịa- Vũng Tàu',
  553: 'H. Côn Đảo - Bà Rịa- Vũng Tàu',
  554: 'H. Đất Đỏ - Bà Rịa- Vũng Tàu',
  555: 'TP Tân An - Long An',
  556: 'H. Tân Hưng - Long An',
  557: 'H. Vĩnh Hưng - Long An',
  558: 'TX Kiến Tường - Long An',
  559: 'H. Tân Thạnh - Long An',
  560: 'H. Thạnh Hóa - Long An',
  561: 'H. Đức Huệ - Long An',
  562: 'H. Đức Hòa - Long An',
  563: 'H. Bến Lức - Long An',
  564: 'H. Thủ Thừa - Long An',
  565: 'H. Châu Thành - Long An',
  566: 'H. Tân Trụ - Long An',
  567: 'H. Cần Đước - Long An',
  568: 'H. Cần Giuộc - Long An',
  684: 'H. Mộc Hóa - Long An',
  569: 'TP Cao Lãnh - Đồng Tháp',
  570: 'TP Sa Đéc - Đồng Tháp',
  571: 'H. Tân Hồng - Đồng Tháp',
  572: 'TX Hồng Ngự - Đồng Tháp',
  573: 'H. Tam Nông - Đồng Tháp',
  574: 'H. Thanh Bình - Đồng Tháp',
  575: 'H. Tháp Mười - Đồng Tháp',
  576: 'H. Cao Lãnh - Đồng Tháp',
  577: 'H. Lấp Vò - Đồng Tháp',
  578: 'H. Lai Vùng - Đồng Tháp',
  579: 'H. Châu Thành - Đồng Tháp',
  685: 'H. Hồng Ngự - Đồng Tháp',
  580: 'TP Long Xuyên - An Giang',
  581: 'TP Châu Đốc - An Giang',
  582: 'H. An Phú - An Giang',
  583: 'TX Tân Châu - An Giang',
  584: 'H. Phú Tân - An Giang',
  585: 'H. Châu Phú - An Giang',
  586: 'H. Tịnh Biên - An Giang',
  587: 'H. Tri Tôn - An Giang',
  588: 'H. Chợ Mới - An Giang',
  589: 'H. Châu Thành - An Giang',
  590: 'H. Thoại Sơn - An Giang',
  591: 'TP Vị Thanh - Hậu Giang',
  592: 'H. Phụng Hiệp - Hậu Giang',
  593: 'H. Vị Thủy - Hậu Giang',
  594: 'TX Long Mỹ - Hậu Giang',
  595: 'H. Châu Thành - Hậu Giang',
  596: 'H. Châu Thành A - Hậu Giang',
  597: 'TX Ngã Bảy - Hậu Giang',
  686: 'H. Long Mỹ - Hậu Giang',
  598: 'TP Mỹ Tho - Tiền Giang',
  599: 'TX Gò Công - Tiền Giang',
  600: 'H. Tân Phước - Tiền Giang',
  601: 'H. Châu Thành - Tiền Giang',
  602: 'TX Cai Lậy - Tiền Giang',
  603: 'H. Chợ Gạo - Tiền Giang',
  604: 'H. Cái Bè - Tiền Giang',
  605: 'H. Gò Công Đông - Tiền Giang',
  606: 'H. Gò Công Tây - Tiền Giang',
  607: 'H. Tân Phú Đông - Tiền Giang',
  710: 'H. Cai Lậy - Tiền Giang',
  608: 'TP Bến Tre - Bến Tre',
  609: 'H. Châu Thành - Bến Tre',
  610: 'H. Chợ Lách - Bến Tre',
  611: 'H. Mỏ Cày Nam - Bến Tre',
  612: 'H. Mỏ Cày Bắc - Bến Tre',
  613: 'H. Bình Đại - Bến Tre',
  614: 'H. Ba Tri - Bến Tre',
  615: 'H. Thạnh Phú - Bến Tre',
  616: 'H. Giồng Trôm - Bến Tre',
  617: 'TP Vĩnh Long - Vĩnh Long',
  618: 'H. Long Hồ - Vĩnh Long',
  619: 'H. Mang Thít - Vĩnh Long',
  620: 'TX Bình Minh - Vĩnh Long',
  621: 'H. Tam Bình - Vĩnh Long',
  622: 'H. Trà Ôn - Vĩnh Long',
  623: 'H. Vũng Liêm - Vĩnh Long',
  624: 'H. Bình Tân - Vĩnh Long',
  625: 'TP Trà Vinh - Trà Vinh',
  626: 'H. Càng Long - Trà Vinh',
  627: 'H. Châu Thành - Trà Vinh',
  628: 'H. Cầu Kè - Trà Vinh',
  629: 'H. Tiểu Cần - Trà Vinh',
  630: 'H. Cầu Ngang - Trà Vinh',
  631: 'H. Trà Cú - Trà Vinh',
  632: 'TX Duyên Hải - Trà Vinh',
  711: 'H. Duyên Hải - Trà Vinh',
  633: 'Q. Ninh Kiều - Cần Thơ',
  634: 'Q. Bình Thủy - Cần Thơ',
  635: 'Q. Ô Môn - Cần Thơ',
  636: 'Q. Cái Răng - Cần Thơ',
  637: 'H. Vĩnh Thạnh - Cần Thơ',
  638: 'H. Cờ Đỏ - Cần Thơ',
  639: 'Q. Thốt Nốt - Cần Thơ',
  640: 'H. Phong Điền - Cần Thơ',
  712: 'H. Thới Lai - Cần Thơ',
  641: 'H. Châu Thành - Sóc Trăng',
  642: 'TP Sóc Trăng - Sóc Trăng',
  643: 'H. Kế Sách - Sóc Trăng',
  644: 'H, Long Phú - Sóc Trăng',
  645: 'H. Mỹ Tú - Sóc Trăng',
  646: 'H. Mỹ Xuyên - Sóc Trăng',
  647: 'H, Thạnh Trị - Sóc Trăng',
  648: 'TX Vĩnh Châu - Sóc Trăng',
  649: 'H. Cù Lao Dung - Sóc Trăng',
  650: 'TX Ngã Năm - Sóc Trăng',
  713: 'H. Trần Đề - Sóc Trăng',
  651: 'TP Rạch Giá - Kiên Giang',
  652: 'TX Hà Tiên - Kiên Giang',
  653: 'H. Hòn Đất - Kiên Giang',
  654: 'H. Tân Hiệp - Kiên Giang',
  655: 'H. Châu Thành - Kiên Giang',
  656: 'H. Giồng Riềng - Kiên Giang',
  657: 'H. Gò Quao - Kiên Giang',
  658: 'H. An Biên - Kiên Giang',
  659: 'H. An Minh - Kiên Giang',
  660: 'H. Vĩnh Thuận - Kiên Giang',
  661: 'H. Phú Quốc - Kiên Giang',
  662: 'H. Kiên Hải - Kiên Giang',
  663: 'H. U Minh Thượng - Kiên Giang',
  664: 'H. Kiên Lương - Kiên Giang',
  715: 'H. Giang Thành - Kiên Giang',
  665: 'TP Bạc Liêu - Bạc Liêu',
  666: 'H. Phước Long - Bạc Liêu',
  667: 'H. Vĩnh Lợi - Bạc Liêu',
  668: 'TX Giá Rai - Bạc Liêu',
  669: 'H. Đông Hải - Bạc Liêu',
  670: 'H. Hòa Bình - Bạc Liêu',
  671: 'H. Hồng Dân - Bạc Liêu',
  672: 'TP Cà Mau - Cà Mau',
  673: 'H. Thới Bình - Cà Mau',
  674: 'H. U Minh - Cà Mau',
  675: 'H. Trần Văn Thời - Cà Mau',
  676: 'H. Cái Nước - Cà Mau',
  677: 'H. Đầm Dơi - Cà Mau',
  678: 'H. Ngọc Hiến - Cà Mau',
  679: 'H. Phù Tân - Cà Mau',
  680: 'H. Năm Căn - Cà Mau',
  714: 'Chưa xác định - Chưa xác định',
};
