/**
 * Copyright (C) SaigonMD, Inc - All Rights Reserved
 * Licensed under the MIT license.
 * Written by Tran Quan <tranquan221b@gmail.com>, Jan 2018
 */

// APP
export const CHAT_CENTER_STATE = 'CHAT_CENTER_STATE';

// THREAD
// --------------------------------------------------
export const IS_FETCH_THREADS_PROCESSING = 'IS_FETCH_THREADS_PROCESSING';
export const IS_THREADS_CAN_LOAD_MORE = 'IS_THREADS_CAN_LOAD_MORE';
export const ALL_THREADS = 'ALL_THREADS';
export const OPENING_THREADS = 'OPENING_THREADS';

export const BLOCKED_USER_LIST = 'BLOCKED_USER_LIST ';
export const IS_GETTING_BLOCKED_USER_LIST = 'IS_GETTING_BLOCKED_USER_LIST ';
export const BLOCKED_THREAD_LIST = 'BLOCKED_THREAD_LIST ';

// CHAT
// --------------------------------------------------
export const CHAT_THREAD = 'CHAT_THREAD';

export const IS_FETCH_CHAT_MESSAGES_PROCESSING = 'IS_FETCH_CHAT_MESSAGES_PROCESSING';
export const IS_FETCH_CHAT_NEW_MESSAGES_PROCESSING = 'IS_FETCH_CHAT_NEW_MESSAGES_PROCESSING';
export const IS_CHAT_MESSAGES_CAN_LOADMORE = 'IS_CHAT_MESSAGES_CAN_LOADMORE';
export const CHAT_MESSAGES = 'CHAT_MESSAGES';
export const IS_CHAT_MESSAGES_ADDED = 'IS_CHAT_MESSAGES_ADDED';
export const APPEND_CHAT_MESSAGES = 'APPEND_CHAT_MESSAGES';
export const PREPEND_CHAT_MESSAGES = 'PREPEND_CHAT_MESSAGES';
export const CHAT_NEW_MESSAGE = 'CHAT_NEW_MESSAGE';
export const CHAT_MESSAGE_CHANGE = 'CHAT_MESSAGE_CHANGE';

export const IS_CHAT_IMAGES_CAN_LOADMORE = 'IS_CHAT_IMAGES_CAN_LOADMORE';
export const CHAT_IMAGES = 'CHAT_IMAGES';
export const APPEND_CHAT_IMAGES = 'APPEND_CHAT_IMAGES';
export const IS_FETCHING_CHAT_IMAGE_MESSAGES = 'IS_FETCHING_CHAT_IMAGE_MESSAGES';

export const CHAT_VIDEOS = 'CHAT_VIDEOS';
export const APPEND_CHAT_VIDEOS = 'APPEND_CHAT_VIDEOS';
export const IS_FETCHING_CHAT_VIDEO_MESSAGES = 'IS_FETCHING_CHAT_VIDEO_MESSAGES';

export const UPDATE_TYPING_THREAD = 'UPDATE_TYPING_THREAD';

// MESSAGE
// --------------------------------------------------
export const CURRENT_THREAD_MESSAGES = '';
export const NEW_MESSAGE = '';
export const UPDATE_MESSAGE = '';


// NOTIFICATION
// --------------------------------------------------
export const IS_REGISTER_FIREBASE_TOKEN_PROCESSING = 'IS_REGISTER_FIREBASE_TOKEN_PROCESSING';
export const REGISTER_FIREBASE_TOKEN_RESPONSE = 'REGISTER_FIREBASE_TOKEN_RESPONSE';
export const PENDING_NOTIFICATION = 'PENDING_NOTIFICATION';
export const IS_GET_NOTIFICATIONS_PROCESSING = 'IS_GET_NOTIFICATIONS_PROCESSING';
export const GET_NOTIFICATIONS_RESPONSE = 'GET_NOTIFICATIONS_RESPONSE';
export const NOTIFICATIONS = 'NOTIFICATIONS';
export const APPEND_NOTIFICATIONS = 'APPEND_NOTIFICATIONS';
export const COUNT_UNREAD_NOTIFICATIONS = 'COUNT_UNREAD_NOTIFICATIONS';

export const COUNT_UNREAD_NOTIFICATIONS_FB = 'COUNT_UNREAD_NOTIFICATIONS_FB';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const READ_ALL_NOTIFICATION = 'READ_ALL_NOTIFICATION';
