const PATH = `../../assets/emoji`;

export const STICKER_DOG = [
  { uid: `dog_1`, icon: require(`${PATH}/dog_1.png`) },
  { uid: `dog_2`, icon: require(`${PATH}/dog_2.png`) },
  { uid: `dog_3`, icon: require(`${PATH}/dog_3.png`) },
  { uid: `dog_4`, icon: require(`${PATH}/dog_4.png`) },
  { uid: `dog_5`, icon: require(`${PATH}/dog_5.png`) },
  { uid: `dog_6`, icon: require(`${PATH}/dog_6.png`) },
  { uid: `dog_7`, icon: require(`${PATH}/dog_7.png`) },
  { uid: `dog_8`, icon: require(`${PATH}/dog_8.png`) },
  { uid: `dog_9`, icon: require(`${PATH}/dog_9.png`) },
  { uid: `dog_10`, icon: require(`${PATH}/dog_10.png`) },
  { uid: `dog_11`, icon: require(`${PATH}/dog_11.png`) },
  { uid: `dog_12`, icon: require(`${PATH}/dog_12.png`) },
  { uid: `dog_13`, icon: require(`${PATH}/dog_13.png`) },
  { uid: `dog_14`, icon: require(`${PATH}/dog_14.png`) },
  { uid: `dog_15`, icon: require(`${PATH}/dog_15.png`) },
  { uid: `dog_16`, icon: require(`${PATH}/dog_16.png`) },
  { uid: `dog_17`, icon: require(`${PATH}/dog_17.png`) },
];

export const STICKER_CAT = [
  { uid: `cat_1`, icon: require(`${PATH}/cat_1.png`) },
  { uid: `cat_2`, icon: require(`${PATH}/cat_2.png`) },
  { uid: `cat_3`, icon: require(`${PATH}/cat_3.png`) },
  { uid: `cat_4`, icon: require(`${PATH}/cat_4.png`) },
  { uid: `cat_5`, icon: require(`${PATH}/cat_5.png`) },
  { uid: `cat_6`, icon: require(`${PATH}/cat_6.png`) },
  { uid: `cat_7`, icon: require(`${PATH}/cat_7.png`) },
  { uid: `cat_8`, icon: require(`${PATH}/cat_8.png`) },
  { uid: `cat_9`, icon: require(`${PATH}/cat_9.png`) },
  { uid: `cat_10`, icon: require(`${PATH}/cat_10.png`) },
  { uid: `cat_11`, icon: require(`${PATH}/cat_11.png`) },
  { uid: `cat_12`, icon: require(`${PATH}/cat_12.png`) },
  { uid: `cat_13`, icon: require(`${PATH}/cat_13.png`) },
  { uid: `cat_14`, icon: require(`${PATH}/cat_14.png`) },
  { uid: `cat_15`, icon: require(`${PATH}/cat_15.png`) },
  { uid: `cat_16`, icon: require(`${PATH}/cat_16.png`) },
  { uid: `cat_17`, icon: require(`${PATH}/cat_17.png`) },
];

export const STICKER_PIG = [
  { uid: `pig_1`, icon: require(`${PATH}/pig_1.png`) },
  { uid: `pig_2`, icon: require(`${PATH}/pig_2.png`) },
  { uid: `pig_3`, icon: require(`${PATH}/pig_3.png`) },
  { uid: `pig_4`, icon: require(`${PATH}/pig_4.png`) },
  { uid: `pig_5`, icon: require(`${PATH}/pig_5.png`) },
  { uid: `pig_6`, icon: require(`${PATH}/pig_6.png`) },
  { uid: `pig_7`, icon: require(`${PATH}/pig_7.png`) },
  { uid: `pig_8`, icon: require(`${PATH}/pig_8.png`) },
  { uid: `pig_9`, icon: require(`${PATH}/pig_9.png`) },
  { uid: `pig_10`, icon: require(`${PATH}/pig_10.png`) },
  { uid: `pig_11`, icon: require(`${PATH}/pig_11.png`) },
  { uid: `pig_12`, icon: require(`${PATH}/pig_12.png`) },
  { uid: `pig_13`, icon: require(`${PATH}/pig_13.png`) },
  { uid: `pig_14`, icon: require(`${PATH}/pig_14.png`) },
  { uid: `pig_15`, icon: require(`${PATH}/pig_15.png`) },
  { uid: `pig_16`, icon: require(`${PATH}/pig_16.png`) },
  { uid: `pig_17`, icon: require(`${PATH}/pig_17.png`) },
];

export const STICKER_MONEY = [
  { uid: `money_1`, icon: require(`${PATH}/money_1.png`) },
  { uid: `money_2`, icon: require(`${PATH}/money_2.png`) },
  { uid: `money_3`, icon: require(`${PATH}/money_3.png`) },
  { uid: `money_4`, icon: require(`${PATH}/money_4.png`) },
  { uid: `money_5`, icon: require(`${PATH}/money_5.png`) },
  { uid: `money_6`, icon: require(`${PATH}/money_6.png`) },
  { uid: `money_7`, icon: require(`${PATH}/money_7.png`) },
  { uid: `money_8`, icon: require(`${PATH}/money_8.png`) },
  { uid: `money_9`, icon: require(`${PATH}/money_9.png`) },
  { uid: `money_10`, icon: require(`${PATH}/money_10.png`) },
  { uid: `money_11`, icon: require(`${PATH}/money_11.png`) },
  { uid: `money_12`, icon: require(`${PATH}/money_12.png`) },
  { uid: `money_13`, icon: require(`${PATH}/money_13.png`) },
  { uid: `money_14`, icon: require(`${PATH}/money_14.png`) },
  { uid: `money_15`, icon: require(`${PATH}/money_15.png`) },
  { uid: `money_16`, icon: require(`${PATH}/money_16.png`) },
  { uid: `money_17`, icon: require(`${PATH}/money_17.png`) },
  { uid: `money_18`, icon: require(`${PATH}/money_18.png`) },
  { uid: `money_19`, icon: require(`${PATH}/money_19.png`) },
  { uid: `money_20`, icon: require(`${PATH}/money_20.png`) },
  { uid: `money_21`, icon: require(`${PATH}/money_21.png`) },
  { uid: `money_22`, icon: require(`${PATH}/money_22.png`) },
];
