// all storage keys used in the app

export const Keys = {
  KEY: 'KEY',
};

export const AsyncStorageKeys = {
  DEVICE_TOKEN: 'DEVICE_TOKEN',
  FCM_TOKEN: 'FCM_TOKEN',
  MY_USER: 'MY_USER',
  APP_INFO: 'APP_INFO',
  DISTRICT: 'DISTRICT',
  SUPPORT_LINE: 'SUPPORT_LINE',
  LAST_TIME_EVENT_LAUNCH: 'LAST_TIME_EVENT_LAUNCH',
  LAST_TIME_EVENT_REFRESH: 'LAST_TIME_EVENT_REFRESH',
  GUILD_SLIDER: 'GUILD_SLIDER',
  GUILD_SHOW: 'GUILD_SHOW',
  LAST_USER_INFO: 'LAST_USER_INFO',
  POPUP_SURVEY_USER: 'POPUP_SURVEY_USER',
  LIST_FINANCE: 'LIST_FINANCE',
  LIST_POST_TIPS: 'LIST_POST_TIPS',
  NEW_USER_GUILD: 'NEW_USER_GUILD',
  LAST_VERSION_CODE: 'LAST_VERSION_CODE',
  RECENT_SEARCH: 'RECENT_SEARCH',
  REFFERAL_CODE: 'REFFERAL_CODE',
  MANUAL_CHECK_EKYC: 'MANUAL_CHECK_EKYC',
  LIST_ID_RSM: 'LIST_ID_RSM',
  IS_HIDE_POPUP_CONFIRM_DELETE_CUSTOMER: 'IS_HIDE_POPUP_CONFIRM_DELETE_CUSTOMER',
  IS_HIDE_GUILD_CUSTOMER_DETAIL: 'IS_HIDE_GUILD_CUSTOMER_DETAIL',
  IS_HIDE_GUILD_PENDING_CUSTOMER_DETAIL: 'IS_HIDE_GUILD_PENDING_CUSTOMER_DETAIL',
  LIST_REFERRAL_HISTORY: 'LIST_REFERRAL_HISTORY',
  IS_HIDE_ALERT_PRIORITY_CUSTOMER_PENDING: 'IS_HIDE_ALERT_PRIORITY_CUSTOMER_PENDING',
  IS_HIDE_ALERT_TRASH_CUSTOMER_PENDING: 'IS_HIDE_ALERT_TRASH_CUSTOMER_PENDING',

  USER_GUIDE: 'USER_GUIDE',
  IS_HIDE_GUILD_BANNER: 'IS_HIDE_GUILD_BANNER',
};

export const TrackingEvents = {
  // FIRST_LOGIN: 'FIRST_LOGIN',
  LOGIN_TOKEN: 'LOGIN_TOKEN',
  USER_LOGIN: 'USER_LOGIN', // when user press login
  USER_LOGOUT: 'USER_LOGOUT', // when user press logout
  APP_REFRESH: 'APP_REFRESH', // when user active app from background
  APP_LAUNCH: 'APP_LAUNCH', // when user lauch app
  SIGN_CONTRACT: 'SIGN_CONTRACT', // when user confirmed Contract Collaborators
  FINISH_KYC: 'FINISH_KYC', // định danh thành công (require location)
  FINISH_ADD_NEW_BANK: 'FINISH_ADD_NEW_BANK', // thêm tk ngân hàng liên kết thành công (require location).
  FINISH_TAX_NUMBER: 'FINISH_TAX_NUMBER',
  FINISH_TAX_COMMITTED: 'FINISH_TAX_COMMITTED',
  UPDATE_NICKNAME: 'UPDATE_NICKNAME',
  UPDATE_METADATA_BASIC: 'UPDATE_METADATA_BASIC',
  UPDATE_METADATA_ADVANCE: 'UPDATE_METADATA_ADVANCE',
  USER_WORKING_BEHAVIOR: 'USER_WORKING_BEHAVIOR',
  MTRADE: 'MTRADE',
};

export const GENDER_LIST = [
  {
    label: 'Nam',
    key: 'Nam',
    isSelected: false,
    value: 'male',
  },
  {
    label: 'Nữ',
    key: 'Nu',
    isSelected: false,
    value: 'female',
  },
];

export const eventName = {
  VIEW_PRODUCT_LOAN: 'LOAN_PRODUCT_IN_VIEW',
  VIEW_APPLY_JOB: 'APPLY_JOB_IN_VIEW',
  INTRODUCE_LOAN_PRODUCT: 'INTRODUCE_LOAN_PRODUCT',
};

export const DEVICE_EVENT_EMITTER = {
  USER_LEVEL: 'USER_LEVEL',
  FILTER_UNREAD_NOTIFICATION: 'FILTER_UNREAD_NOTIFICATION',
  CHANGE_COLLABORATOR_TAB_INDEX: 'CHANGE_COLLABORATOR_TAB_INDEX',
  COLLABORATOR_REFRESH: 'COLLABORATOR_REFRESH',
  HANDLE_LOAD_MORE_LIST_COLLABORATOR: 'HANDLE_LOAD_MORE_LIST_COLLABORATOR',
  HANDLE_LOAD_MORE_LIST_COLLABORATOR_REVIEW: 'HANDLE_LOAD_MORE_LIST_COLLABORATOR_REVIEW',
};
