require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
flutter_application_path = '../forked_node_modules/flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

use_frameworks! :linkage => :static

pre_install do |installer|
  installer.pod_targets.each do |pod|
   if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
      def pod.build_type;
        Pod::BuildType.static_library # I assume you use CocoaPods >= 1.9
      end
    end
  end
end

target 'mfast' do
  ### Resolve Conflict Firebase // START
  #   https://github.com/juliansteenbakker/mobile_scanner/issues/335#issuecomment-1308829103
  #   https://issuetracker.google.com/issues/254418199#comment48

  # scr: https://github.com/CocoaPods/Specs/blob/master/Specs/8/1/e/MLKitVision/5.0.0/MLKitVision.podspec.json
  pod 'MLKitVision', :podspec => 'MLKitVision.podspec.json'
  # scr: https://github.com/CocoaPods/Specs/blob/master/Specs/c/c/6/MLKitCommon/9.0.0/MLKitCommon.podspec.json
  pod 'MLKitCommon', :podspec => 'MLKitCommon.podspec.json'
  ### Resolve Conflict Firebase // END

  use_frameworks! :linkage => :static
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  install_all_flutter_pods(flutter_application_path)
  $RNFirebaseAsStaticFramework = true

  # Pods for mfast
  pod 'TouchID', :path => "../node_modules/react-native-touch-id"

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
  pod 'react-native-branch', path: '../node_modules/react-native-branch'



  pod 'TouchID', :path => '../node_modules/react-native-touch-id'


  post_install do |installer|
  ## Fix for XCode 12.5
      find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
      "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
      find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
      "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
        target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          ## dart: PermissionGroup.camera
          'PERMISSION_CAMERA=1',
          ]
        end
      end
      flutter_post_install(installer) if defined?(flutter_post_install)
  end

end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

