import { StyleSheet } from 'react-native';
import { fonts } from '../../constants/configs';
import { SH, SW } from '../../constants/styles';
import Colors from '../../theme/Color';
import { SCREEN_WIDTH } from '../../utils/Utils';
const WIDTH_LIST = SCREEN_WIDTH - SW(32);

export const styles = StyleSheet.create({
  textInput: {
    width: '100%',
    height: SH(40),
    color: Colors.gray1,
    fontSize: SH(14),
    lineHeight: SH(18),
    backgroundColor: Colors.primary5,
    paddingLeft: SW(48),
    borderRadius: 8,
    fontFamily: fonts.regular,
  },
  containerInput: {
    marginTop: SH(16),
  },
  searchIconPosition: {
    position: 'absolute',
    left: SW(18),
    top: SH(13),
    zIndex: 1,
  },
  searchIcon: {
    width: SW(18),
    height: SH(18),
    resizeMode: 'contain',
  },
  deleteIcon: {
    width: SW(14),
    height: SH(14),
    resizeMode: 'contain',
    marginLeft: SW(8),
  },
  paddingView: {
    paddingHorizontal: SW(16),
    marginTop: SH(16),
  },
  avatarImage: {
    width: SW(56),
    height: SW(56),
    borderRadius: SW(28),
    // backgroundColor: 'red',
  },
  containerButton: {
    width: SW(24),
    height: SW(24),
    borderRadius: SW(12),
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconStyle: {
    width: SW(24),
    height: SH(24),
    borderRadius: SW(12),
    borderWidth: 1,
    borderColor: Colors.primary5,
  },
  containerItemRsm: {
    alignItems: 'center',
    minHeight: SH(56),
    // paddingLeft: SW(24),
    width: WIDTH_LIST / 5,
    paddingBottom: SH(16),
  },
  containerDeleteButton: {
    position: 'absolute',
    right: -SH(2),
    top: 0,
  },
  containerFilterButton: {
    marginTop: SH(12),
    paddingHorizontal: SW(16),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.primary5,
    borderRadius: 8,
    paddingVertical: SH(8),
  },
  rowView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  containerItemFilter: {
    backgroundColor: Colors.actionBackground,
    borderRadius: 18,
    height: SH(32),
    justifyContent: 'center',
    alignItems: 'center',
  },
  textItemFilter: {
    color: Colors.gray5,
    fontSize: SH(14),
    lineHeight: SH(20),
    paddingHorizontal: SW(12),
  },
  confirmButtonView: {
    height: SH(46),
    borderRadius: 27,
    backgroundColor: Colors.primary2,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: SW(16),
  },
  paddingBottomSheet: {
    paddingBottom: SH(38),
  },
  bigText: {
    fontSize: SH(16),
    lineHeight: SH(19),
    color: Colors.gray1,
  },
  removeFilterButton: {
    marginTop: SH(20),
    alignItems: 'center',
  },
  messageViewContainer: {
    backgroundColor: Colors.secondBlue,
    paddingHorizontal: SW(16),
    paddingBottom: SH(40),
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  containerTitleMessage: {
    marginTop: SH(16),
    marginBottom: SH(8),
  },
  messageInputContainer: {
    backgroundColor: Colors.primary5,
    fontSize: SH(14),
    lineHeight: SH(20),
    minHeight: SH(80),
    maxHeight: SH(200),
    paddingHorizontal: SW(16),
    paddingVertical: SH(12),
    borderRadius: 8,
    fontFamily: fonts.regular,
    textAlignVertical: 'top',
  },
  containerSubmitButton: {
    marginTop: SH(20),
    alignItems: 'center',
  },
  submitButton: {
    width: SW(180),
    height: SH(48),
    borderRadius: 24,
    backgroundColor: Colors.neutral3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textSubmitButton: {
    fontSize: SH(16),
    lineHeight: SH(19),
    color: Colors.primary5,
  },
  backgroundPopup: {
    backgroundColor: Colors.primary5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    minHeight: SH(212),
    // paddingHorizontal: SW(16),
  },
  headerPopupTextStyle: {
    color: Colors.gray1,
    fontSize: SH(16),
    lineHeight: SH(22),
  },
  popupTextStyle: {
    fontSize: SH(14),
    lineHeight: SH(22),
    color: Colors.gray1,
  },
  imageStyle: {
    height: SH(48),
    width: SW(188),
    resizeMode: 'contain',
    marginTop: SH(20),
  },
  bottomButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#d6dcf7',
    height: SH(53),
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  buttonStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingIconStyle: {
    width: SW(56),
    height: SH(56),
  },
  deleteIconPosition: {
    position: 'absolute',
    right: SW(18),
    top: SH(13),
    zIndex: 1,
  },
  modalView: {
    position: 'absolute',
    top: SH(125),
    left: 0,
    right: 0,
    bottom: 0,
  },
  modalView2: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
    backgroundColor: 'red',
  },
  searchCTVContainer: {
    backgroundColor: Colors.primary5,
    marginTop: SH(12),
    minHeight: SH(82),
    borderRadius: 8,
    paddingVertical: SH(16),
  },
  indicationStyle: {
    width: SW(24),
    height: SH(24),
  },
  marginText: {
    marginLeft: SW(16),
  },
  checkBoxContainer: {
    width: SW(24),
    height: SW(24),
    borderRadius: SW(12),
    borderColor: Colors.gray5,
    borderWidth: 0.75,
  },
  containerItemFiltered: {
    backgroundColor: Colors.primary5,
    borderRadius: 8,
    height: SH(32),
    paddingHorizontal: SW(12),
    justifyContent: 'space-between',
    alignItems: 'center',
    marginRight: SW(8),
    flexDirection: 'row',
  },
  bigAvatarImage: {
    width: SW(80),
    height: SW(80),
    borderRadius: SW(40),
    resizeMode: 'cover',
  },
  containerHeaderButton: {
    width: SW(24),
    height: SW(24),
    borderRadius: SW(12),
    borderWidth: 1,
    borderColor: Colors.gray1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconHeaderButton: {
    width: SW(16),
    height: SW(16),
    resizeMode: 'contain',
    tintColor: Colors.gray1,
  },
  containerItemHistory: {
    backgroundColor: Colors.primary5,
    borderRadius: 8,
    paddingVertical: SH(12),
    paddingHorizontal: SW(12),
    marginBottom: SH(12),
  },
  dotView: {
    width: SW(4),
    height: SH(4),
    backgroundColor: Colors.gray1,
    marginHorizontal: SW(6),
    borderRadius: SW(2),
  },
  containerContentNoti: {
    paddingTop: SH(4),
    paddingBottom: SH(8),
    borderBottomColor: Colors.gray4,
    borderBottomWidth: 0.75,
  },
  containerFooterItemHistory: {
    marginTop: SH(8),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  icon: {
    width: SW(24),
    height: SW(24),
  },
  textNull: {
    fontSize: SH(13),
    lineHeight: SH(18),
    color: Colors.gray5,
    marginTop: SH(13),
  },
  textShowAll: {
    color: Colors.primary2,
    fontSize: SH(14),
    lineHeight: SH(20),
  },
  containerShowAll: {
    alignSelf: 'center',
    height: SH(20),
  },
});
