/**
 * Copyright (C) SaigonMD, Inc - All Rights Reserved
 * Licensed under the MIT license.
 * Written by Tran Quan <tranquan221b@gmail.com>, Jan 2018
 */

// APP
export const RESET_APP_STATE = 'RESET_APP_STATE';
export const PENDING_OPEN_DEEP_LINK = 'PENDING_OPEN_DEEP_LINK';
export const INTERNET_STATE_CHANGE = 'INTERNET_STATE_CHANGE';
export const SYSTEM_AVAILABLE = 'SYSTEM_AVAILABLE';

// NAVIGATION
// --------------------------------------------------
export const ROOT_SCREEN = 'ROOT_SCREEN';
export const HOME_NAVIGATE = 'HOME_NAVIGATE';
export const CURRENT_SCREEN_NAME = 'CURRENT_SCREEN_NAME';

// GENERAL
// --------------------------------------------------
export const UPDATE_APP_INFO = 'UPDATE_APP_INFO';
export const IS_GET_BANKS_PROCESSING = 'IS_GET_BANKS_PROCESSING';
export const GET_BANKS_RESPONSE = 'GET_BANKS_RESPONSE';
export const IS_GET_BANK_BRANCHES_PROCESSING = 'IS_GET_BANK_BRANCHES_PROCESSING';
export const GET_BANKS_BRANCHES_RESPONSE = 'GET_BANKS_BRANCHES_RESPONSE';

// USER
// --------------------------------------------------
export const IS_LOGIN_PROCESSING = 'IS_LOGIN_PROCESSING';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const IS_LOGOUT_PROCESSING = 'IS_LOGOUT_PROCESSING';
export const LOGOUT_RESPONSE = 'LOGOUT_RESPONSE';
export const MY_USER = 'MY_USER';

export const MY_USER_LIST = 'MY_USER_LIST';

export const IS_RESET_PASSWORD_PROCESSING = 'IS_RESET_PASSWORD_PROCESSING';
export const RESET_PASSWORD_RESPONSE = 'RESET_PASSWORD_RESPONSE';
export const RESET_PASSWORD_INFO = 'RESET_PASSWORD_INFO';

export const IS_REGISTER_PROCESSING = 'IS_REGISTER_PROCESSING';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';

export const IS_REGISTER_VALIDATE_PROCESSING = 'IS_REGISTER_VALIDATE_PROCESSING';
export const REGISTER_VALIDATE_RESPONSE = 'REGISTER_VALIDATE_RESPONSE';

export const IS_SEND_PASSWORD_PROCESSING = 'IS_SEND_PASSWORD_PROCESSING';
export const SEND_PASSWORD_RESPONSE = 'SEND_PASSWORD_RESPONSE';

export const IS_UPDATE_PROFILE_PROCESSING = 'IS_UPDATE_PROFILE_PROCESSING';
export const UPDATE_PROFILE_RESPONSE = 'UPDATE_PROFILE_RESPONSE';

export const IS_IMPORTANT_UPDATE_PROFILE_PROCESSING = 'IS_IMPORTANT_UPDATE_PROFILE_PROCESSING';
export const IMPORTANT_UPDATE_PROFILE_RESPONSE = 'IMPORTANT_UPDATE_PROFILE_RESPONSE';

export const IS_GET_OWNERS_PROCESSING = 'IS_GET_OWNERS_PROCESSING';
export const GET_OWNERS_RESPONSE = 'GET_OWNERS_RESPONSE';

export const IS_GET_USERS_PROCESSING = 'IS_GET_USERS_PROCESSING';
export const GET_USERS_RESPONSE = 'GET_USERS_RESPONSE';

export const LOADING_ACCOUNT_DATA = 'LOADING_ACCOUNT_DATA';

// CONTACT
// --------------------------------------------------
export const IS_FETCH_CONTACTS_PROCESSING = 'IS_FETCH_CONTACTS_PROCESSING';
export const ALL_CONTACTS = 'ALL_CONTACTS';

// SUBSCRIPTION
// --------------------------------------------------
export const IS_GET_SUBSCRIPTIONS_PROCESSING = 'IS_GET_SUBSCRIPTION_PROCESSING';
export const GET_SUBSCRIPTIONS_RESPONSE = 'GET_SUBSCRIPTION_RESPONSE';
export const SUBSCRIPTIONS = 'SUBSCRIPTIONS';

// NEWS
// --------------------------------------------------
export const IS_GET_NEWS_PROCESSING = 'IS_GET_NEWS_PROCESSING';
export const GET_NEWS_RESPONSE = 'GET_NEWS_RESPONSE';
export const NOTICE_NEWS = 'NOTICE_NEWS';
export const APPEND_NOTICE_NEWS = 'APPEND_NOTICE_NEWS';
export const COUNT_UNREAD_NOTICE_NEWS = 'COUNT_UNREAD_NOTICE_NEWS';

// KNOWLEDGE
// --------------------------------------------------
export const IS_GET_KNOWLEDGE_PROCESSING = 'IS_GET_KNOWLEDGE_PROCESSING';
export const GET_KNOWLEDGE_RESPONSE = 'GET_KNOWLEDGE_RESPONSE';
export const KNOWLEDGES = 'KNOWLEDGES';
export const APPEND_KNOWLEDGES = 'APPEND_KNOWLEDGES';
export const COUNT_UNREAD_KNOWLEDGES = 'COUNT_UNREAD_KNOWLEDGES';
export const CONTEST = 'CONTEST';

// MONEY
// --------------------------------------------------
export const IS_GET_MONEY_HISTORY_PROCESSING = 'IS_GET_MONEY_HISTORY_PROCESSING';
export const GET_MONEY_HISTORY_RESPONSE = 'GET_MONEY_HISTORY_RESPONSE';
export const MONEY_HISTORY = 'MONEY_HISTORY';
export const APPEND_MONEY_HISTORY = 'APPEND_MONEY_HISTORY';

// GIFT
// --------------------------------------------------
export const IS_GET_GIFTS_PROCESSING = 'IS_GET_GIFTS_PROCESSING';
export const GET_GIFTS_RESPONSE = 'GET_GIFTS_RESPONSE';
export const GIFTS = 'GIFTS';

export const IS_GET_POINTS_HISTORY_PROCESSING = 'IS_GET_POINTS_HISTORY_PROCESSING';
export const GET_POINTS_HISTORY_RESPONSE = 'GET_POINTS_HISTORY_RESPONSE';
export const POINTS_HISTORY = 'POINTS_HISTORY';
export const APPEND_POINTS_HISTORY = 'APPEND_POINTS_HISTORY';

export const IS_REDEEM_GIFT_PROCESSING = 'IS_REDEEM_GIFT_PROCESSING';
export const REDEEM_GIFT_RESPONSE = 'REDEEM_GIFT_RESPONSE';

// NOTIFICATION
// --------------------------------------------------
export const IS_REGISTER_FIREBASE_TOKEN_PROCESSING = 'IS_REGISTER_FIREBASE_TOKEN_PROCESSING';
export const REGISTER_FIREBASE_TOKEN_RESPONSE = 'REGISTER_FIREBASE_TOKEN_RESPONSE';
export const PENDING_NOTIFICATION = 'PENDING_NOTIFICATION';
export const PENDING_NOTIFICATION_LIST = 'PENDING_NOTIFICATION_LIST';
export const IS_GET_NOTIFICATIONS_PROCESSING = 'IS_GET_NOTIFICATIONS_PROCESSING';
export const GET_NOTIFICATIONS_RESPONSE = 'GET_NOTIFICATIONS_RESPONSE';
export const NOTIFICATIONS = 'NOTIFICATIONS';
export const APPEND_NOTIFICATIONS = 'APPEND_NOTIFICATIONS';
export const COUNT_UNREAD_NOTIFICATIONS = 'COUNT_UNREAD_NOTIFICATIONS';

export const COUNT_UNREAD_NOTIFICATIONS_FB = 'COUNT_UNREAD_NOTIFICATIONS_FB';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const READ_ALL_NOTIFICATION = 'READ_ALL_NOTIFICATION';

export const ADD_NOTI_TO_PENDING_LIST = 'ADD_NOTI_TO_PENDING_LIST';
export const REMOVE_NOTI_FROM_PENDING_LIST = 'REMOVE_NOTI_FROM_PENDING_LIST';

// --------------------------------------------------
// HISTORY LOGIN ACTIVITIES
export const IS_GET_LOGIN_ACTIVITY_PROCESSING = 'IS_GET_LOGIN_ACTIVITY_PROCESSING';
export const GET_LOGIN_ACTIVITY_RESPONSE = 'GET_LOGIN_ACTIVITY_RESPONSE';
export const LOGIN_ACTIVITY_RESPONSE = 'LOGIN_ACTIVITY_RESPONSE';
export const APPEND_LOGIN_ACTIVITY = 'APPEND_LOGIN_ACTIVITY';

// --------------------------------------------------
// BANK
export const IS_GET_USER_BANK_LIST = 'IS_GET_USER_BANK_LIST';
export const USER_BANK_LIST_RESPONSE = 'USER_BANK_LIST_RESPONSE';

// --------------------------------------------------
// CUSTOM NEWS
export const IS_GETTING_NEWS_SLIDE_LIST = 'IS_GETTING_NEWS_SLIDE_LIST';
export const NEWS_SLIDE_LIST = 'NEWS_SLIDE_LIST';

// --------------------------------------------------
// APP LIST
export const IS_GETTING_USER_APP_LIST = 'IS_GETTING_USER_APP_LIST';
export const USER_APP_LIST = 'USER_APP_LIST';
export const IS_GETTING_USER_APP_LIGHT_LIST = 'IS_GETTING_USER_APP_LIGHT_LIST';
export const USER_APP_LIGHT_LIST = 'USER_APP_LIGHT_LIST';

// --------------------------------------------------
// BAD LOAN
export const IS_GETTING_USER_BAD_LOAN = 'IS_GETTING_USER_BAD_LOAN';
export const USER_BAD_LOAN = 'USER_BAD_LOAN ';

// --------------------------------------------------
// PROMOTION
export const PROMOTION_EVENT = 'PROMOTION_EVENT ';

export const ACTIVE_TABBAR_EVENT = 'ACTIVE_TABBAR_EVENT ';

export const CONTEST_ITEM = 'CONTEST_ITEM ';

export const BLOCKED_USER_LIST = 'BLOCKED_USER_LIST ';
export const IS_GETTING_BLOCKED_USER_LIST = 'IS_GETTING_BLOCKED_USER_LIST ';
export const BLOCKED_THREAD_LIST = 'BLOCKED_THREAD_LIST ';

export const UPDATE_SIP = 'UPDATE_SIP';
export const CREATE_ACC_SIP = 'CREATE_ACC_SIP';
export const CALL_SIP = 'CALL_SIP';
export const TERMINATE_CALL_SIP = 'TERMINATE_CALL_SIP';

export const HELP_EVENT = 'HELP_EVENT ';

export const FETCHING_SHOP_ITEMS = 'FETCHING_SHOP_ITEMS';
export const SHOP_ITEMS = 'SHOP_ITEMS';

export const FETCHING_SHOP_V2_ITEMS = 'FETCHING_SHOP_ITEMS';
export const SHOP_V2_ITEMS = 'SHOP_ITEMS';
export const MAIN_GROUP = 'MAIN_GROUP';

export const DEL_MOD = 'DEL_MOD';

export const WITHDRAW_INFOS = 'WITHDRAW_INFOS';
export const WITHDRAW_TERM = 'WITHDRAW_TERM';

// --------------------------------------------------
// FINANCIAL SERVICES
export const FETCHING_FINANCIAL_SERVICES = 'FETCHING_FINANCIAL_SERVICES';
export const FINANCIAL_SERVICES = 'FINANCIAL_SERVICES';

// --------------------------------------------------
// CUSTOMER PRODUCT FORMS
export const FETCHING_CUSTOMER_FORMS = 'FETCHING_CUSTOMER_FORMS';
export const CUSTOMER_FORMS = 'CUSTOMER_FORMS';
export const CUSTOMER_FORMS_LIST_DISTRICT = 'CUSTOMER_FORMS_LIST_DISTRICT';
export const CUSTOMER_FORM_FIND_DISTRICTS_BY_TEXT = 'CUSTOMER_FORM_FIND_DISTRICTS_BY_TEXT';

export const FINANCIAL_CUSTOMER_FORM = 'FINANCIAL_CUSTOMER_FORM';
export const DIGITAL_WALLET_CUSTOMER_FORM = 'DIGITAL_WALLET_CUSTOMER_FORM';
export const INSURANCE_CUSTOMER_FORM = 'INSURANCE_CUSTOMER_FORM';
export const TOP_UP_CUSTOMER_FORM = 'TOP_UP_CUSTOMER_FORM';
export const MAKEMONEY_CUSTOMER_FORM = 'MAKEMONEY_CUSTOMER_FORM';
export const MOBILE_CARD_CUSTOMER_FORM = 'MOBILE_CARD_CUSTOMER_FORM';
export const SOLAR_CUSTOMER_FORM = 'SOLAR_CUSTOMER_FORM';
export const MOBILECARD_AND_TOPUP_FORM = 'MOBILECARD_AND_TOPUP_FORM';

// --------------------------------------------------
// MOBILE CARD PAYMENT URL
export const FETCHING_MOBILE_CARD_PAYMENT_URL_DATA = 'FETCHING_MOBILE_CARD_PAYMENT_URL_DATA';
export const MOBILE_CARD_PAYMENT_URL_DATA = 'MOBILE_CARD_PAYMENT_URL_DATA';

// --------------------------------------------------
// GLOBAL CARE
export const FETCHING_GLOBAL_CARE_URL_DATA = 'FETCHING_GLOBAL_CARE_URL_DATA';
export const GLOBAL_CARE_URL_DATA = 'GLOBAL_CARE_URL_DATA';

/*  OTP
 */

export const SENDING_OTP = 'SENDING_OTP';
export const SENDING_OTP_RESULLT = 'SENDING_OTP_RESULT';
export const REQUEST_WITH_OTP_RESULT = 'REQUEST_WITH_OTP_RESULT ';

// --------------------------------------------------
// FEEDBACK OSTICKET
export const FETCHING_OS_TICKET_TOPICS = 'FETCHING_OS_TICKET_TOPICS';
export const OS_TICKET_TOPICS = 'OS_TICKET_TOPICS';

export const FETCHING_LIST_OS_TICKET_BY_USER_ID = 'FETCHING_LIST_OS_TICKET_BY_USER_ID';
export const LIST_OS_TICKET_BY_USER_ID = 'LIST_OS_TICKET_BY_USER_ID';
export const TOTAL_LIST_OS_TICKET_BY_USER_ID = 'TOTAL_LIST_OS_TICKET_BY_USER_ID';

export const FETCHING_THREAD_BY_TICKET_ID = 'FETCHING_THREAD_BY_TICKET_ID';
export const THREAD_BY_TICKET_ID = 'THREAD_BY_TICKET_ID';

export const CREATING_AN_OS_TICKET = 'CREATING_AN_OS_TICKET';
export const CREATE_AN_OS_TICKET_RESPONSE = 'CREATE_AN_OS_TICKET_RESPONSE';

export const POSTING_THREAD = 'POSTING_THREAD';
export const POST_THREAD_RESPONSE = 'POST_THREAD_RESPONSE';

// CONTACT

export const FETCHING_CONVERSATION_CONTACTS = 'FETCHING_CONVERSATION_CONTACTS';
export const CONVERSATION_CONTACTS = 'CONVERSATION_CONTACTS';
export const INVITATIONS_REQUESTS_CONTACT = 'INVITATIONS_REQUESTS_CONTACT';

// TOOLS
export const HOME_TOOLS = 'HOME_TOOLS';

// --------------------------------------------------
// TOPUP PAYMENT URL
export const FETCHING_TOPUP_PAYMENT_URL_DATA = 'FETCHING_TOPUP_PAYMENT_URL_DATA';
export const TOPUP_STATUS = 'TOPUP_STATUS';

export const POST_LIST = 'POST_LIST';
export const INVITATION = 'INVITATION';

// DPD
export const DPD_DATA = 'DPD_DATA';

// LOADING
export const IS_LOADING = 'IS_LOADING';

// POPUP
export const SET_POPUP_BRAND = 'SET_POPUP_BRAND';
export const SET_SHOW_POPUP_BRAND = 'SET_SHOW_POPUP_BRAND';

// posts tips
export const POSTS_TIPS = 'GET/POSTS_TIPS';

// posts tips
export const LIST_FINANCE = 'GET/LIST_FINANCE';

export const IS_FETCHING_SINGLE_CHAT = 'IS_FETCHING_SINGLE_CHAT';
