// LOADING
export const SET_LOADING_COMMON = 'SET_LOADING_COMMON';
export const SET_LOADING_PHONE_OTP = 'SET_LOADING_PHONE_OTP';
export const SET_LOADING_ADDBANKING = 'SET_LOADING_ADDBANKING';
export const SET_LOADING_UPDATE_USER_META = 'SET_LOADING_UPDATE_USER_META';
export const SET_LOADING_TAX_NUMBER = 'SET_LOADING_TAX_NUMBER';
export const SET_LOADING_GET_U_META = 'SET_LOADING_GET_U_META';

// USER CONFIG
export const GET_USER_CONFIG = 'GET_USER_CONFIG';
export const SET_USER_CONFIG = 'SET_USER_CONFIG';
export const SET_USER_PASSCODE = 'SET_USER_PASSCODE';
export const SET_ENABLE_NOTE = 'SET_ENABLE_NOTE';
export const SET_USER_DELETE_ACCOUNT = 'SET_USER_DELETE_ACCOUNT';
export const SET_OVERVIEW_CORE_AGENT = 'SET_OVERVIEW_CORE_AGENT';
export const SET_TIME_CHECKING = 'SET_TIME_CHECKING';
export const SET_STATISTIC_WORKING = 'SET_STATISTIC_WORKING';

// USER META
export const SET_USER_META_DATA = 'SET_USER_META_DATA';
export const UPDATE_USER_META_STEP = 'UPDATE_USER_META_STEP';
export const UPDATE_USER_META = 'UPDATE_USER_META';

// BANKING
export const SET_LIST_BANKS = 'SET_LIST_BANKS';
export const SET_LIST_BANK_BRANCHES = 'SET_LIST_BANK_BRANCHES';
export const SET_LIST_MY_BANKING = 'SET_LIST_MY_BANKING';
export const ADD_MY_BANKING = 'ADD_MY_BANKING';
export const SET_KBANK_DATA = 'SET_KBANK_DATA';
export const SET_BIDV_DATA = 'SET_BIDV_DATA';

// TAX
export const SEND_TAX_COMMIT = 'SEND_TAX_COMMIT';

// ARENA
export const SET_ARENA_INFOR = 'SET/ARENA_INFOR';

// ARENA
export const SET_THREAD_PUBLIC = 'SET/THREAD_PUBLIC';
export const SET_HIGHTLIGHT_PROJECTS = 'SET_HIGHTLIGHTS_PROJECT';

//CTV

export const SET_LIST_CTVS = 'SET_LIST_CTVS';
export const SET_MORE_LIST_CTVS = 'SET_MORE_LIST_CTVS';
export const SET_LIST_NOTIS = 'SET_LIST_NOTIS';

// RSM PUSH MESSAGE

export const SET_LIST_RSM_PUSH_MESSAGE = 'SET_LIST_RSM_PUSH_MESSAGE';
export const ADD_RSM_PUSH_MESSAGE = 'ADD_RSM_PUSH_MESSAGE';

// CUSTOMER TAB

export const SET_LIST_FILTER_CUSTOMER = 'SET_LIST_FILTER_CUSTOMER';
export const SET_TOTAL_NUM_TAB = 'SET_TOTAL_NUM_TAB';
export const SET_CURRENT_NUM_TAB = 'SET_CURRENT_NUM_TAB';
export const SET_LIST_CUSTOMER = 'SET_LIST_CUSTOMER';
export const SET_MORE_LIST_CUSTOMER = 'SET_MORE_LIST_CUSTOMER';
export const SET_LIST_CUSTOMER_PENDING = 'SET_LIST_CUSTOMER_PENDING';
export const SET_MORE_LIST_CUSTOMER_PENDING = 'SET_MORE_LIST_CUSTOMER_PENDING';
export const SET_LIST_CUSTOMER_TRASH = 'SET_LIST_CUSTOMER_TRASH';
export const SET_MORE_LIST_CUSTOMER_TRASH = 'SET_MORE_LIST_CUSTOMER_TRASH';

export const ADD_PRIORITY_CUSTOMER = 'ADD_PRIORITY_CUSTOMER';
export const REMOVE_PRIORITY_CUSTOMER = 'REMOVE_PRIORITY_CUSTOMER';

export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';

export const SET_LIST_CUSTOMER_LINK = 'SET_LIST_CUSTOMER_LINK';
export const SET_MORE_LIST_CUSTOMER_LINK = 'SET_MORE_LIST_CUSTOMER_LINK';
export const REMOVE_CUSTOMER_LINK = 'REMOVE_CUSTOMER_LINK';

export const SET_TOTAL_NUM_LINK_TAB = 'SET_TOTAL_NUM_LINK_TAB';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const SET_TAB_INDEX_CUSTOMER = 'SET_TAB_INDEX_CUSTOMER';

// COLLABORATOR TAB
export const SET_COLLABORATOR_CURRENT_INDEX = 'SET_COLLABORATOR_CURRENT_INDEX';
export const SET_HIER_INFO_USER = 'SET_HIER_INFO_USER';
export const SET_LEGEND_CHART = 'SET_LEGEND_CHART';
export const SET_EXP_CHART = 'SET_EXP_CHART';
export const SET_COM_CHART = 'SET_COM_CHART';
export const SET_COLLABORATOR_CHART = 'SET_COLLABORATOR_CHART';
export const SET_LIST_PL_REFERRAL = 'SET_LIST_PL_REFERRAL';
export const SET_LIST_PL_REFERRAL_HISTORY = 'SET_LIST_PL_REFERRAL_HISTORY';
export const SET_MY_SUPPORTER = 'SET_MY_SUPPORTER';
export const SET_FILTER_RATING = 'SET_FILTER_RATING';

export const SET_TAB_INDEX_COLLABORATOR = 'SET_TAB_INDEX_COLLABORATOR';

export const SET_LIST_INSURANCE_REFERRAL = 'SET_LIST_INSURANCE_REFERRAL';
export const SET_LIST_INSURANCE_REFERRAL_HISTORY = 'SET_LIST_INSURANCE_REFERRAL_HISTORY';

export const SET_LIST_DAA_REFERRAL = 'SET_LIST_DAA_REFERRAL';
export const SET_LIST_DAA_REFERRAL_HISTORY = 'SET_LIST_DAA_REFERRAL_HISTORY';
// NOTIFICATION

export const SET_LIST_NOTIFICATION = 'SET_LIST_NOTIFICATION';
export const SET_MORE_LIST_NOTIFICATION = 'SET_MORE_LIST_NOTIFICATION';
export const SET_FILTER_NOTIFICATION = 'SET_FILTER_NOTIFICATION';
export const READ_NOTIFICATION_NEW = 'READ_NOTIFICATION_NEW';
export const READ_ALL_NOTIFICATION_NEW = 'READ_ALL_NOTIFICATION_NEW';
export const UNREAD_NOTIFICATION_NEW = 'UNREAD_NOTIFICATION_NEW';
export const FLAG_NOTIFICATION = 'FLAG_NOTIFICATION';
export const SET_TOTAL_UNREAD_NOTIFICATION = 'SET_TOTAL_UNREAD_NOTIFICATION';
export const INCREASE_TOTAL_UNREAD_NOTIFICATION = 'INCREASE_TOTAL_UNREAD_NOTIFICATION';

// MTRADE
export const SET_LIST_MAIN_BANNER = 'SET_LIST_MAIN_BANNER';
export const SET_LIST_MAIN_PRODUCT = 'SET_LIST_MAIN_PRODUCT';
export const SET_LIST_MTRADE_BANNER = 'SET_LIST_MTRADE_BANNER';
export const SET_LIST_MTRADE_CATEGORY = 'SET_LIST_MTRADE_CATEGORY';
export const SET_LIST_MTRADE_FILTER = 'SET_LIST_MTRADE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';
export const RESET_TEXT_SEARCH = 'RESET_TEXT_SEARCH';
export const SET_FILTER = 'SET_FILTER';
export const SET_TEXT_SEARCH = 'SET_TEXT_SEARCH';
export const SET_LIST_MTRADE_PRODUCT = 'SET_LIST_MTRADE_PRODUCT';
export const SET_MORE_LIST_MTRADE_PRODUCT = 'SET_MORE_LIST_MTRADE_PRODUCT';
export const SET_LIST_MTRADE_LOCATION = 'SET_LIST_MTRADE_LOCATION';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_LIST_MTRADE_PRODUCT_HISTORY = 'SET_LIST_MTRADE_PRODUCT_HISTORY';
export const ADD_ITEM_LIST_MTRADE_PRODUCT_HISTORY = 'ADD_ITEM_LIST_MTRADE_PRODUCT_HISTORY';
export const SET_LIST_MTRADE_CARD = 'SET_LIST_MTRADE_CARD';
export const SET_MORE_LIST_MTRADE_CARD = 'SET_MORE_LIST_MTRADE_CARD';
export const ADD_ITEM_LIST_MTRADE_CARD = 'ADD_ITEM_LIST_MTRADE_CARD';
export const REMOVE_ITEM_LIST_MTRADE_CARD = 'REMOVE_ITEM_LIST_MTRADE_CARD';
export const SET_MTRADE_CODE = 'SET_MTRADE_CODE';
export const SET_MTRADE_BONUS = 'SET_MTRADE_BONUS';

// CHAT
export const SET_TOTAL_UNREAD_CHAT = 'SET_TOTAL_UNREAD_CHAT';
export const INCREASE_TOTAL_UNREAD_CHAT = 'INCREASE_TOTAL_UNREAD_CHAT';
