import { Platform, StyleSheet } from 'react-native';
import { SH, SW } from '../../../constants/styles';

import Colors from '../../../theme/Color';

export default StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: Colors.actionBackground,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.actionBackground,
  },
  pathImage: {
    flex: 1,
    borderRadius: 8,
  },

  icAdd: {
    width: 24,
    height: 24,
  },
  indicator: {
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'center',
    color: Colors.primary2,
    marginTop: 10,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topIndicatorLeft: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: Colors.gray1,
  },
  topIndicatorRight: {
    fontSize: 14,
    fontStyle: 'normal',
    letterSpacing: 0,
    color: Colors.primary2,
    marginTop: 2,
  },
  txtDow: {
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: Colors.primary2,
    paddingRight: 8,
  },
  btContainer: {
    paddingHorizontal: SW(41),
    marginVertical: SH(10),
  },
  bottomBoxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: Colors.primary5,
    marginVertical: 8,
  },
  indicatorBottom: {
    fontSize: 14,
    letterSpacing: 0,
    color: Colors.primary2,
    marginRight: 12,
    flex: 1,
    lineHeight: 18,
  },
  iconContainer: {
    position: 'absolute',
    right: -8,
    top: -8,
  },
  resultContainer: {
    borderRadius: 6,
    backgroundColor: '#ffeee0',
    padding: 12,
    marginBottom: 16,
  },
  indicatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  raw: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  icPending: {
    width: 20,
    height: 20,
  },
  indicatorStatus: {
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'right',
    color: Colors.sixOrange,
    marginLeft: 6,
  },
  indicatorLabel: {
    opacity: 0.6,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: Colors.primary4,
  },
  indicatorDesc: {
    flex: 1,
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
  },
  resultContainerFailure: {
    borderRadius: 6,
    backgroundColor: '#ffe1e5',
    padding: 12,
    marginBottom: 16,
  },
  resultContainerSuccess: {
    borderRadius: 6,
    backgroundColor: '#d3ffe4',
    padding: 12,
    marginBottom: 16,
  },
  indicatorStatusSuccess: {
    fontSize: 13,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'right',
    color: Colors.green5,
  },
  indicatorStatusFailure: {
    fontSize: 13,
    lineHeight: 16,
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'right',
    color: Colors.sixRed,
    marginLeft: 6,
  },
  icFailure: {
    width: 16,
    height: 16,
    tintColor: Colors.sixRed,
  },
  indicatorLabelFailure: {
    opacity: 0.6,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: Colors.primary3,
  },
  indicatorDescFailure: {
    flex: 1,
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
  },
  indicatorDescSuccess: {
    flex: 1,
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
  },
  labelInput: {
    fontSize: SH(14),
    lineHeight: SH(20),
    textAlign: 'center',
    color: Colors.gray1,
    marginBottom: SH(16),
  },
  cmndIdNumber: {
    fontSize: 17,
    fontWeight: '700',
    fontStyle: 'normal',
    lineHeight: 24,
    letterSpacing: 0,
    textAlign: 'center',
    color: Colors.primary1,
  },
  warningWrapper: {
    flex: 1,
  },
  smbol: {
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: Colors.primary4,
    marginRight: 8,
  },
  lineWarning: {
    flex: 1,
    marginTop: 5,
    marginBottom: 5,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  indicatorWarning: {
    flex: 1,
    fontSize: 14,
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 22,
    letterSpacing: 0,
    color: Colors.primary4,
  },
  descWarning: {
    flex: 1,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 22,
    letterSpacing: 0,
    color: Colors.primary4,
  },
  highlight: {
    color: Colors.accent3,
    fontWeight: '500',
  },
  bottonIndicator: {
    opacity: 0.8,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: 0,
    color: Colors.primary4,
    marginTop: 20,
  },
  updateImage: {
    width: SW(140),
    height: SH(120),
    resizeMode: 'contain',
    marginBottom: SH(16),
    marginTop: SH(20),
  },
  imageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.neutral5,
    marginLeft: 44,
    aspectRatio: 299 / 192,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  circleNumber: {
    width: 32,
    height: 32,
    borderRadius: 32 / 2,
    backgroundColor: '#d6deff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  number: {
    fontSize: 18,
    lineHeight: 26,
    color: '#221db0',
    marginTop: Platform.OS === 'ios' ? 2 : 0,
  },
});
