import { StyleSheet } from 'react-native';

import Colors from '.././../../theme/Color';
import { SCREEN_WIDTH } from '../../../utils/Utils';

export default StyleSheet.create({
  wrapper: {
    flex: 1,
    width: SCREEN_WIDTH,
    backgroundColor: Colors.neutral5,
  },
  importCMNDContainer: {
    paddingVertical: 20,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
  },
  identifyCardContainer: {
    marginVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inforVerifyContainer: {
    flex: 1,
    paddingHorizontal: 16,
    backgroundColor: Colors.neutral5,
  },
  boxVerify: {
    borderRadius: 6,
    backgroundColor: '#fff',
    padding: 16,
  },
  indicatorBottomContainer: {
    paddingVertical: 16,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topIndicator: {
    opacity: 0.6,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: Colors.primary4,
  },
  wraningIndicator: {
    fontSize: 12,
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: Colors.accent3,
    marginRight: 10,
  },
  descWraningIndicator: {
    flex: 1,
    opacity: 0.8,
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: Colors.primary4,
    marginVertical: 5,
  },
  suggestIndicator: {
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: Colors.primary2,
  },
  importIndicator: {
    opacity: 0.8,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: Colors.primary4,
    marginTop: 20,
    marginBottom: 12,
  },
  itemVerifyContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  labelTxt: {
    opacity: 0.6,
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: Colors.primary4,
  },
  divider: {
    height: 12,
  },
  valueTxt: {
    flex: 1,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'right',
    color: Colors.primary4,
    marginLeft: 30,
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  indicatorError: {
    flex: 1,
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    lineHeight: 17,
    marginLeft: 6,
    color: Colors.accent3,
  },
  sendSupportContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 6,
  },
  icCheck: {
    width: 24,
    height: 24,
    marginRight: 7,
    tintColor: Colors.primary2,
  },
  txtCheckNormal: {
    flex: 1,
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    opacity: 0.8,
    color: Colors.primary4,
  },
  txtChecked: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: Colors.primary4,
  },
  note: {
    flex: 1,
    borderRadius: 6,
    backgroundColor: Colors.primary5,
    borderWidth: 1,
    borderColor: Colors.neutral4,
    height: 65,
    marginTop: 10,
    textAlignVertical: 'top',
    padding: 12,
  },
  checkboxContainer: {
    marginTop: 16,
  },
  ic: {
    width: 24,
    height: 24,
  },
  successTxt: {
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    color: Colors.accent1,
  },
  successContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
  },
  errorDupContainer: {
    borderRadius: 5,
    backgroundColor: '#ffe2e6',
    borderStyle: 'solid',
    borderWidth: 0.5,
    borderColor: Colors.accent3,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 16,
  },
  txtErrorDup: {
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: Colors.accent3,
    paddingVertical: 13,
    marginLeft: 6,
  },
});
